### PR TITLE
Distinguish hash-getter from hash-comparison infix operators

### LINKED ISSUE #1371: Bug: Space around operator isn't working
Hi !

**Describe the bug**

I have a case where ocamlformat removes the space around a custom infix operator.

**How to Reproduce**

Version: 0.14.2

Original file
```ocaml
let formula_base x =
    let open Formula.Infix in
    (Expr.typeof x) #== (Lit (Type IntType))
    #&& (x #<= (Expr.int 4))
    #&& ((Expr.int 0) #< x)
```

Produced diff:
```ocaml
- #&& ((Expr.int 0) #< x)
+ #&& ((Expr.int 0)#<x)
```

Config:
```
profile=default
quiet=false
max-iters=10
comment-check=true
wrap-fun-args=true
wrap-comments=false
type-decl-indent=2
type-decl=compact
stritem-extension-indent=0
space-around-variants=true
space-around-records=true
space-around-lists=true
space-around-arrays=true
single-case=compact
sequence-style=terminator
sequence-blank-line=preserve-one
parse-docstrings=false
parens-tuple-patterns=multi-line-only
parens-tuple=always
parens-ite=false
ocp-indent-compat=false
nested-match=wrap
module-item-spacing=sparse
max-indent=68
match-indent-nested=never
match-indent=0
margin=80
let-open=preserve
let-module=compact
let-binding-spacing=compact
let-binding-indent=2
let-and=compact
leading-nested-match-parens=false
infix-precedence=indent
indicate-nested-or-patterns=unsafe-no
indicate-multiline-delimiters=space
indent-after-in=0
if-then-else=compact
function-indent-nested=never
function-indent=2
field-space=loose
extension-sugar=preserve
extension-indent=2
exp-grouping=parens
escape-strings=preserve
escape-chars=preserve
dock-collection-brackets=true
doc-comments-tag-only=default
doc-comments-padding=2
doc-comments-val=unset
doc-comments=before (file .ocamlformat:11)
disambiguate-non-breaking-match=false
disable=false
cases-matching-exp-indent=normal
cases-exp-indent=4
break-struct=force
break-string-literals=auto
break-sequences=true
break-separators=after
break-infix-before-func=false
break-infix=wrap
break-fun-sig=smart (file .ocamlformat:10)
break-fun-decl=smart (file .ocamlformat:9)
break-collection-expressions=fit-or-vertical (file .ocamlformat:8)
break-cases=fit-or-vertical (file .ocamlformat:7)
break-before-in=fit-or-vertical (file .ocamlformat:6)
assignment-operator=end-line (file .ocamlformat:5)
align-variants-decl=true (file .ocamlformat:4)
align-constructors-decl=true (file .ocamlformat:3)
align-cases=true (file .ocamlformat:2)
```

### PR DESCRIPTION
**Pull request by gpetiot**
fix #1371

### CODE REVIEW

File: lib/Ast.ml [hunk 1]
```diff
@@ -77,6 +77,17 @@ let is_infix e =
   | Pexp_ident {txt= Lident i; _} -> is_infix_id i
   | _ -> false
 
+let is_hash_getter_id i =
+  let is_infix_char = function
+    | '$' | '%' | '*' | '+' | '-' | '/' | '<' | '=' | '>' | '|' | '&' | '@'
+     |'^' | '#' | '.' ->
```
Comment (Julow) [inline lib/Ast.ml:83]: This list is already in `is_infix_id`. Could you factorize the code ?
