### PR TITLE
Fix cmts in list

### LINKED ISSUE #652: Bad formating of comment in list
When a comment is in last position of a list, it doesn't get indented the same way as the other elements in the list.

Before ocamlformat:

```ocaml
let l =
  [ "Lorem ipsum dolor sit amet, consectetur adipiscing elit";
    (* ", sed do eiusmod tempor incididunt ut labore et dolore"; *)
    "sed do eiusmod tempor incididunt ut labore et dolore";
    (* " magna aliqua. Ut enim ad minim veniam, quis nostrud "; *)
    (* "exercitation ullamco laboris nisi ut aliquip ex ea commodo " *)
  ]
```

After:

```ocaml
let l =
  [ "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
  ; (* ", sed do eiusmod tempor incididunt ut labore et dolore"; *)
    "sed do eiusmod tempor incididunt ut labore et dolore"
  (* " magna aliqua. Ut enim ad minim veniam, quis nostrud "; *)
  (* "exercitation ullamco laboris nisi ut aliquip ex ea commodo " *)
   ]
```

Also, when using `space-around-collection-expression=true`, a space is inserted after the last comment.

```
[@@@ocamlformat "space-around-collection-expressions=true"]

let l =
  [ "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
  ; (* ", sed do eiusmod tempor incididunt ut labore et dolore"; *)
    "sed do eiusmod tempor incididunt ut labore et dolore"
  (* " magna aliqua. Ut enim ad minim veniam, quis nostrud "; *)
  (* "exercitation ullamco laboris nisi ut aliquip ex ea commodo " *)
  
  ]
```

### PR DESCRIPTION
**Pull request by gpetiot**
Fix #652 
The diff of test_branch looks good.

### CODE REVIEW

File: src/Fmt_ast.ml [hunk 1]
```diff
@@ -323,7 +323,8 @@ let fmt_variance = function
 let fmt_private_flag flag = fmt_if Poly.(flag = Private) "@ private"
 
 let wrap_list c =
-  if c.conf.space_around_collection_expressions then wrap "[ " "@ ]"
+  if c.conf.space_around_collection_expressions then fun k ->
+    fmt "[ " $ k $ or_newline "]" "]"
```
Comment (gpetiot) [inline src/Fmt_ast.ml]: It looks like these modifications are not needed for the other wrap_* functions

File: test/passing/list_pattern.ml [hunk 2]
```diff
@@ -4,3 +4,42 @@ let _ =
...
+      ; (* ", sed do eiusmod tempor incididunt ut labore et dolore"; *)
+        "sed do eiusmod tempor incididunt ut labore et dolore"
+        (* " magna aliqua. Ut enim ad minim veniam, quis nostrud "; *)
+        (* "exercitation ullamco laboris nisi ut aliquip ex ea commodo " *)
+       ]
+    ; (* ", sed do eiusmod tempor incididunt ut labore et dolore"; *)
+      "sed do eiusmod tempor incididunt ut labore et dolore"
+      (* " magna aliqua. Ut enim ad minim veniam, quis nostrud "; *)
+      (* "exercitation ullamco laboris nisi ut aliquip ex ea commodo " *)
+     ] ->
```
Comment (Julow) [inline test/passing/list_pattern.ml]: Unecessary space here and above

Comment (gpetiot) [reply test/passing/list_pattern.ml]: Yes, didn't find a simple way to fix that, but at least it's not a regression caused by this PR (already in issue77.ml for example) and I don't think it's directly linked to this issue so we could fix it in another PR (better to keep the two diff's apart).
