### PR TITLE
fix break-struct for toplevel items (not in a struct)

### LINKED ISSUE #490: Weird module + include formating with break-struct=natural
When my .ocamlformat configuration file contains `break-struct=natural`, I get pretty weird formatting in a file that contains only a module and an include. They end up both on the same line. This behavior doesn't happen when there is more content in the file.

The .ocamlformat file:

```
break-struct=natural
```

Original file:

```ocaml
module Json = Yojson.Basic

include B
```

Results in:

```ocaml
module Json = Yojson.Basic include B
```

But a file with more content:

```ocaml
module Json = Yojson.Basic

include EsMappingShared

module T = struct
  let v = x
  let y = 100
  let z = 200
end

module Y = struct let v = x end
```

Ends up in a normal formatting:

```ocaml
module Json = Yojson.Basic
include EsMappingShared

module T = struct
  let v = x

  let y = 100

  let z = 200
end

module Y = struct let v = x end
```

### PR DESCRIPTION
**Pull request by gpetiot**
Should fix #490

### CODE REVIEW

File: src/Fmt_ast.ml [hunk 1]
```diff
@@ -3719,20 +3719,21 @@ and fmt_structure c ctx itms =
     List.group itms ~break:(fun (itmI, cI) (itmJ, cJ) ->
         Ast.break_between c.cmts (Str itmI, cI.conf) (Str itmJ, cJ.conf) )
   in
+  let break_struct = c.conf.break_struct || not in_struct in
```
Comment (jberdine) [inline src/Fmt_ast.ml]: I think it would be better to look at `ctx` instead of passing an extra arg.
