### PR TITLE
Fix: formatting of end line comments

### LINKED ISSUE #660: Bad formatting of end line comments
Hi !
Using the latest version of ocamlformat, and default settings,
```
include Bar (* this is commenting the include line *)
```
was formatted to 
```
include Bar

(* this is commenting the include line *)
```
Wouldn't it be better to move the comment above the code than two lines below ? This seems like a semantic change.

### PR DESCRIPTION
**Pull request by gpetiot**
Fix #660 
Overall the comment placement is closer to the original source.

The new breaks on the `[%%foo:   ...  ]` seem to be more consistent (discriminating on the context to only break for toplevel extensions does not seem to work).

### CODE REVIEW

File: test/passing/object.ml [hunk 1]
```diff
@@ -30,7 +30,8 @@ let _ =
 
     constraint t = 'a t
 
-    [%%ext salut, "hello"]
+    [%%ext
+    salut, "hello"]
```
Comment (Julow) [inline test/passing/object.ml]: Why this change ? It's not related to comments.

Comment (gpetiot) [reply test/passing/object.ml]: It was due to the added hvbox around the structure_item and the comments after, sometimes the break was expected for the extensions, even if it fitted on one line (but not always).
I finally put the hvbox only if there are comments after, to reduce the diff.

File: test/passing/comments.ml.opts [hunk 2]
```diff
@@ -1 +1 @@
---max-iter=3
\ No newline at end of file
+--max-iter=4
```
Comment (Julow) [inline test/passing/comments.ml.opts]: Does this means that this PR make Ocamlformat a little slower ?

File: test/passing/js_source.ml.ref [hunk 3]
```diff
@@ -8809,7 +8799,6 @@ external t : float -> float = "t" [@@unboxed]
 
 let _ = ignore ( + )
 let _ = raise Exit 3
-
 (* comment 9644 of PR#6000 *)
```
Comment (Julow) [inline test/passing/js_source.ml.ref]: Why this one is not on the same line ?

File: test/passing/comments.ml.opts (hunk 2 above)
Comment (gpetiot) [reply test/passing/comments.ml.opts]: That means we need an extra iteration yes (the reason is not obvious from my changes though)

File: test/passing/js_source.ml.ref (hunk 3 above)
Comment (gpetiot) [reply test/passing/js_source.ml.ref]: fixed

**Comment by gpetiot** [comment]
The changes on the `[%%foo .... ]` extensions are due to the new hvbox, but the output is closer to the input code anyway.

File: test/passing/comments.ml.opts (hunk 2 above)
Comment (gpetiot) [reply test/passing/comments.ml.opts]: fixed

**Comment by gpetiot** [comment]
I fixed all the regressions, should be ready to go now.

@pascutto does it look better on the codebase you have been formatting?
