### PR TITLE
Fix comment dropped in field alias

### LINKED ISSUE #844: Bug: Comment dropped.
```
$ (echo "let x = { aaaaaaaaaa = aaaaaaaaaa "; echo "(* b *); b = b }")  | _build/dev/src/ocamlformat.exe - --name a.ml
ocamlformat.exe: Cannot process "a.ml".
  Please report this bug at https://github.com/ocaml-ppx/ocamlformat/issues.
  BUG: comments dropped.
File "a.ml", line 2, characters 0-7:
Error: Comment (* b *) dropped.
EXIT STATUS 1
```

### PR DESCRIPTION
**Pull request by gpetiot**
Fix #844, no regression with test_branch.

### CODE REVIEW

File: test/passing/record.ml [hunk 1]
```diff
@@ -106,3 +106,5 @@ let _ = x {a: string = a'; b= (b' : string)}
 let x = function {a= (_ : string); _} -> ()
 
 let x = function {a: string = _; _} -> ()
+
+let x = {aaaaaaaaaa (* b *); b}
```
Comment (hhugo) [inline test/passing/record.ml]: Can you add an example with a new line like 
```ocaml
let x =
  { aaaaaaaaaa
  (* b *)
  ; b}
```

Comment (gpetiot) [reply test/passing/record.ml]: done
