### PR TITLE
Fix: comment in empty structure

### LINKED ISSUE #798: Comment dropped.
```
$ echo "include A (struct (* a *) end)" | _build/release/src/ocamlformat.exe --name a.ml -
ocamlformat.exe: Cannot process "a.ml".
  Please report this bug at https://github.com/ocaml-ppx/ocamlformat/issues.
  BUG: comments dropped.
File "a.ml", line 1, characters 18-25:
Error: Comment (* a *) dropped.
EXIT STATUS 1
```

### PR DESCRIPTION
**Pull request by gpetiot**
Fix #798 
The test_branch diff is empty.

### CODE REVIEW

File: test/passing/module.ml [hunk 1]
```diff
@@ -43,3 +43,11 @@ with type t := t
...
   let () = ()
 end
+
+include struct
+  (* a *)
+end
+
+include A (struct
+  (* a *)
+end)
```
Comment (Julow) [inline test/passing/module.ml]: Shouldn't this be `include A ( (* a *) )` ?

Comment (gpetiot) [reply test/passing/module.ml]: I chose to keep the original behavior that is to have the `struct`/`end` keywords if the structure is non-empty, and the structure is not empty since there is at least one comment.

Comment (Julow) [reply test/passing/module.ml]: I agree. Implementing this is extremely tricky anyway, as the comment inside the parenthesis is placed juste after the lid.

Comment (gpetiot) [reply test/passing/module.ml]: And by the way if we omit the keywords, the comment is placed before `( )` and not inside.
