### PR TITLE
Handle lazy patterns as arguments to class

### LINKED ISSUE #1261: Bug: crash when using a pattern as an argument to class expression
Hi,

The following program crashes ocamlformat:

    class t (lazy _) = object end

(The output is missing parens around `lazy _`)

### PR DESCRIPTION
**Pull request by emillon**
Fixes #1261

### CODE REVIEW

File: lib/Ast.ml [hunk 1]
```diff
@@ -1985,6 +1985,7 @@ end = struct
      |Cl {pcl_desc= Pcl_fun _; _}, Ppat_tuple _
      |Cl {pcl_desc= Pcl_fun _; _}, Ppat_construct _
      |Cl {pcl_desc= Pcl_fun _; _}, Ppat_alias _
+     |Cl {pcl_desc= Pcl_fun _; _}, Ppat_lazy _
```
Comment (Julow) [inline lib/Ast.ml]: Some more cases are missing:
- `Ppat_exception`
- `Ppat_variant` with arguments
- `Ppat_or`

I wonder if a refactor of this function is needed. What do you thing of classifying the context argument separately (eg. to `` Patern of pattern | Function | Let | Parameter ``), so we have saner rules that can't forget any cases ?

Comment (emillon) [reply lib/Ast.ml]: I don't think that Ppat_exception can be found here, but yes this looks more complicated than it should. To be fair, I'm not sure I understand why `parenze_x` functions are structured this way, compared to assigning precedence levels and comparing them.

Comment (Julow) [reply lib/Ast.ml]: I think these functions are this way because we did let that happen :( Now it's time to improve them !
Computing precedence would be great but a lot more work.

Comment (emillon) [reply lib/Ast.ml]: OK I'll have a look at this.

Comment (emillon) [reply lib/Ast.ml]: it's likely that we can improve, and @CraigFe has started in this direction, but this is not strictly related to this PR
