### PR TITLE
Fix break-separators=after-and-docked for record patterns

### LINKED ISSUE #926: incoherent formatting for records
With ocamlformat 0.10, it seems that the records are not formatted the same way when they are pattern matched on or when they are created. Here are two examples. When pattern matching the first field is on the same line than `{`. When creating a new record, the first field is on a different line.

```ocaml
let f () =
  let { aaaaaaaa;
    bbbbbbbbbb;
      ccccccccc;
        dddddddddd;
        eeeeeeeee;
        ffffffffff;
        gggggggggg;
        hhhhhhhhhh;
        iiiiiiiiii;
        jjjjjjjjjjj
      }
    =
    some_value
  in
  {
    aaaaaaaa;
    bbbbbbbbbb;
    ccccccccc;
    dddddddddd;
    eeeeeeeee;
    ffffffffff;
    gggggggggg;
    hhhhhhhhhh;
    iiiiiiiiii;
    jjjjjjjjjjj;
  }

let g () =
  match some_value with
  | { aaaaaaaa;
    bbbbbbbbbb;
      ccccccccc;
      dddddddddd;
      eeeeeeeee;
      ffffffffff;
      gggggggggg;
      hhhhhhhhhh;
      iiiiiiiiii;
      jjjjjjjjjjj
    } ->
    {
      aaaaaaaa;
      bbbbbbbbbb;
      ccccccccc;
      dddddddddd;
      eeeeeeeee;
      ffffffffff;
      gggggggggg;
      hhhhhhhhhh;
      iiiiiiiiii;
      jjjjjjjjjjj;
    }
```

```
break-cases=toplevel
break-infix-before-func=false
break-infix=fit-or-vertical
break-separators=after-and-docked
break-sequences=true
break-struct=natural
cases-exp-indent=2
doc-comments=before
exp-grouping=preserve
field-space=loose
indicate-multiline-delimiters=closing-on-separate-line
indicate-nested-or-patterns=unsafe-no
leading-nested-match-parens=true
let-and=sparse
m=120
max-indent=2
nested-match=align
ocp-indent-compat=true
parens-ite=true
parens-tuple=multi-line-only
sequence-blank-line=preserve-one
sequence-style=terminator
space-around-arrays=true
space-around-lists=true
space-around-records=true
space-around-variants=true
type-decl=sparse
wrap-fun-args=true
```

### PR DESCRIPTION
**Pull request by gpetiot**
Fix #926, the diff of test_branch looks good.
@Khady feel free to give us feedback.

### CODE REVIEW

File: src/Params.ml [hunk 1]
```diff
@@ -144,6 +144,39 @@ let get_record_expr (c : Conf.t) =
...
+  in
+  match c.break_separators with
+  | `Before | `After -> r
+  | `After_and_docked ->
+      let space = if c.space_around_records then 1 else 0 in
+      let indent_opn, indent_cls =
+        match ctx with
+        | Ast.Exp {pexp_desc= Pexp_match _ | Pexp_try _; _} -> (-1, -1)
+        | Ast.Exp {pexp_desc= Pexp_let _; _} -> (-2, -2)
+        | _ -> (2, -2)
```
Comment (Julow) [inline src/Params.ml]: Couldn't the calling code be changed so it's always `0, -2` and avoid looking at the context ?

**Comment by Khady** [comment]
The diff of the tests also looks good to me. I don't have much time to test the change on our whole codebase, sorry about that.

File: src/Params.ml (hunk 1 above)
Comment (gpetiot) [reply src/Params.ml]: I don't think we could avoid looking at the context since I want the indentation to depend on where the pattern is.
