### PR TITLE
Preserve begin-end keywords around infix operators

### LINKED ISSUE #1594: Bug: exp-grouping is not respected around binary operators
The `begin` and `end` keywords are not preserved when `--exp-grouping=preserve` is set on the command line.

**How to Reproduce**

1. Create a file `test.ml` with the following contents:
  ```ocaml
  let () =
      begin
          add_test @@
          let test_name = "Test 1" in
          test_name >:: fun _ ->
              assert_equal "a" "a"
      end;
      begin
          add_test @@
          let test_name = "Test 2" in
          test_name >:: fun _ ->
              assert_equal "b" "b"
      end;
  ```

2. Run `ocamlformat --enable-outside-detected-project --exp-grouping=preserve test.ml`

The output of the above command is, in my 0.15.0 install, as follows:

```ocaml
let () =
  ( add_test
  @@
  let test_name = "Test 1" in
  test_name >:: fun _ -> assert_equal "a" "a" );
  add_test
  @@
  let test_name = "Test 2" in
  test_name >:: fun _ -> assert_equal "b" "b"
```

Note that `begin` and `end` have been replaced by `(` and `)`.

Interestingly, this does *not* happen unless the `@@` operator appears in the block.  The code

```ocaml
  let () =
      begin
          let test_name = "Test 1" in
          test_name >:: fun _ ->
              assert_equal "a" "a"
      end;
      begin
          let test_name = "Test 2" in
          test_name >:: fun _ ->
              assert_equal "b" "b"
      end;
  ```

transforms to

```ocaml
let () =
  begin
    let test_name = "Test 1" in
    test_name >:: fun _ -> assert_equal "a" "a"
  end;
  let test_name = "Test 2" in
  test_name >:: fun _ -> assert_equal "b" "b"
```

(Note: in the original artifact that inspired this bug report, the context in which the two `begin`-`end` blocks appear is within a `List.iteri`: hence why they are grouped together in this fashion.  I rather wish I could find a way to convince `ocamlformat` not to remove the last pair of "unnecessary" `begin`-`end` tokens as they help readability.)

Thank you!

### PR DESCRIPTION
**Pull request by gpetiot**
Fix #1594, no diff with test_branch.sh

### CODE REVIEW

File: test/passing/tests/extensions-indent.ml.ref [hunk 1]
```diff
@@ -361,17 +361,45 @@ let _ = f [%ext new x]
...
+let _ =
+  [%ext
+       begin
+         y >>= z
+       end]
 
-let _ = [%ext y >>= z]
+let _ =
+  [%ext
+       begin
```
Comment (Julow) [inline test/passing/tests/extensions-indent.ml.ref:372]: This indentation looks like a bug. Should be 2 or 4 but not the column it broke.

File: lib/Fmt_ast.ml [hunk 2]
```diff
@@ -1528,11 +1528,18 @@ and fmt_infix_op_args c ~parens xexp op_args =
...
+  with
+  | `Parens ->
+      wrap_if_k
+        (parens || Ast.parenze_nested_exp xexp)
+        (fits_breaks "(" opn)
+        (fits_breaks ")" ?hint cls)
+        (list_fl groups fmt_op_arg_group)
+  | `Begin_end ->
+      wrap "begin@;<1 2>@[<0>" "@]@;<1000 0>end"
+        (list_fl groups fmt_op_arg_group)
```
Comment (Julow) [inline lib/Fmt_ast.ml:1542]: Can't this be calling `wrap_exp` below ?

File: lib/Fmt_ast.ml [hunk 3]
```diff
@@ -1520,18 +1520,14 @@ and fmt_infix_op_args c ~parens xexp op_args =
            $ fmt_if_k (not last) (break 1 0) ) )
     $ fmt_if_k (not last_grp) (break 1 0)
   in
-  let opn, hint, cls =
-    if parens || Poly.(c.conf.infix_precedence = `Parens) then
```
Comment (gpetiot) [inline lib/Fmt_ast.ml:1524]: The `infix-precedence` option is not taken into consideration anymore, but the diff produced by test_branch.sh still looks good, only a few parens have been added.
We could remove this option since it is not used anymore anywhere else in ocamlformat.

File: lib/Fmt_ast.ml (hunk 2 above)
Comment (gpetiot) [reply lib/Fmt_ast.ml]: I've done that now, a few changes in parens, but the code is much easier to maintain, and some cases of breaking the margin have been solved in the testbase.

File: test/passing/tests/extensions-indent.ml.ref (hunk 1 above)
Comment (gpetiot) [reply test/passing/tests/extensions-indent.ml.ref:372]: This indentation is due to the option `--extension-indent=5` for this file

Comment (Julow) [reply test/passing/tests/extensions-indent.ml.ref:372]: right!

File: lib/Fmt_ast.ml (hunk 3 above)
Comment (Julow) [reply lib/Fmt_ast.ml:1524]: This option was used only here, it looks like you just un-implemented that option.

File: lib/Fmt_ast.ml (hunk 2 above)
Comment (gpetiot) [reply lib/Fmt_ast.ml]: Right, so I think it's better to just keep the first commit, wrap_exp does not fit this usecase

Comment (Julow) [reply lib/Fmt_ast.ml:1542]: What's the reason ?

Comment (gpetiot) [reply lib/Fmt_ast.ml]: The code was too different from `wrap_exp`, I tried to merge both into one, but there was arguments/options only used for this "infix_op_arg" usecase and others only used for the general case, so in my last commit I chose to rename `Params.wrap_exp` as `Params.Exp.wrap` and define a new function `Params.Exp.Infix_op_arg.wrap` to use here (in future PRs I would like to put more expression-related functions into the Exp module)

**Review by Julow — COMMENTED** [review]
Sorry for the slow reply. I think this is good.
