### PR TITLE
Fix dropped attributes in with_constraints

### LINKED ISSUE #842: Bug : ast changed.
```
$ echo "include (List : module type of Pervasives with module A := A [@warning \"-3\"] with module B := B)"  | _build/dev/src/ocamlformat.exe - --name a.ml
ocamlformat.exe: Cannot process "a.ml".
  Please report this bug at https://github.com/ocaml-ppx/ocamlformat/issues.
  BUG: ast changed.
EXIT STATUS 1
```

### PR DESCRIPTION
**Pull request by gpetiot**
Fix #842, with test_branch: minor changes (less pretty but better attachment) similar to the changes in source.ml/js_source.ml:

```ocaml
diff --git a/sledge/src/import/import.ml b/sledge/src/import/import.ml
index 84013e28c..aa6cd884c 100644
--- a/sledge/src/import/import.ml
+++ b/sledge/src/import/import.ml
@@ -24,8 +24,8 @@ include (
          and module Format := Base.Format
          and module Marshal := Base.Marshal
          and module Scanf := Base.Scanf
-         and type ('ok, 'err) result := ('ok, 'err) Base.result)
-      [@warning "-3"]
+         and type ('ok, 'err) result := ('ok, 'err) Base.result [@warning
+                                                                  "-3"])
     end )
 
 (* undeprecate *)
diff --git a/sledge/src/import/import.mli b/sledge/src/import/import.mli
index 9d3b583a3..7d541460b 100644
--- a/sledge/src/import/import.mli
+++ b/sledge/src/import/import.mli
@@ -24,8 +24,8 @@ include module type of (
          and module Format := Base.Format
          and module Marshal := Base.Marshal
          and module Scanf := Base.Scanf
-         and type ('ok, 'err) result := ('ok, 'err) Base.result)
-      [@warning "-3"]
+         and type ('ok, 'err) result := ('ok, 'err) Base.result [@warning
+                                                                  "-3"])
     end )
```

### CODE REVIEW

File: test/passing/attributes.ml [hunk 1]
```diff
@@ -43,15 +43,18 @@ let[@inline always] f x =
...
   module T (S : S [@test]) : S
 
-  module T : (S with type t = (r[@test3])) [@test4]
+  module T : (S with type t = (r[@test3]) [@test4])
 
   module T :
-    (S with type t = t and type u := u and module R = R and module S := S)
-  [@test]
+    (S
+    with type t = t
```
Comment (Julow) [inline test/passing/attributes.ml]: Shouldn't this be indented by 1?

Comment (gpetiot) [reply test/passing/attributes.ml]: It should be 2, fixed

Comment (Julow) [reply test/passing/attributes.ml]: Not one more because of the parens ?
