### PR TITLE
Fix unstable comments around attributes

### LINKED ISSUE #1025: Bug: unstable comment between attributes
**Describe the bug**
If I run ocamlformat on the following file...
```
module M = struct
  type t
  [@@immediate]
  (* ______________________________________ *)
  [@@deriving variants, sexp_of]
end
```

...I get the following error:
```
ocamlformat: Cannot process "app/apply-style/feedback/comment_between_attributes.ml".
  Please report this bug at https://github.com/ocaml-ppx/ocamlformat/issues.
  BUG: formatting did not stabilize after 10 iterations.
```

**How to Reproduce**
This is using ocamlformat built from 63e1d3ab131ca8b5f2809c0d6fdfafdf749fe1b9, using the flags `--profile=janestreet --enable-outside-detected-project --disable-conf-files`.

### PR DESCRIPTION
**Pull request by gpetiot**
Fix #1025
also contains some simplfications to `fmt_type_declaration` that are small enough to be squeezed in this PR (I thought the issue was specific to type declarations at first so I started cleaning a bit).

No diff with test_branch with and without using the janestreet profile (the issue is due to the `margin=90` actually).

### CODE REVIEW

File: src/Fmt_ast.ml [hunk 1]
```diff
@@ -616,7 +616,8 @@ and fmt_attributes c ?(pre = noop) ?(suf = noop) ~key attrs =
   let num = List.length attrs in
   let fmt_attr ~first ~last {attr_name; attr_payload; attr_loc} =
     fmt_or_k first (open_hvbox 0) (fmt "@ ")
-    $ Cmts.fmt c attr_loc (fmt_attribute c key (attr_name, attr_payload))
+    $ hvbox 0
+        (Cmts.fmt c attr_loc (fmt_attribute c key (attr_name, attr_payload)))
```
Comment (gpetiot) [inline src/Fmt_ast.ml]: The fix is here, other changes are simplifications.

**Comment by gpetiot** [comment]
Tested again with the fixed version of test_branch.
