### PR TITLE
Fix: parens around expressions with attributes

### LINKED ISSUE #439: Expressions with attributes are sometimes not parenthesized correctly
echo "let () = f (object end [@imp Show])" | _build/dev/src/ocamlformat.exe --name a.ml -

### PR DESCRIPTION
**Pull request by gpetiot**
Should fix #439

### CODE REVIEW

**Comment by hhugo** [comment]
#439 is not specific to objects, we have the same issue with many other expression I believe.

File: test/passing/js_source.ml.ref [hunk 1]
```diff
@@ -103,7 +103,7 @@ let () =
       done ) [@foo]];
   [%foo (assert true [@foo])];
   [%foo (lazy x) [@foo]];
-  [%foo (object end) [@foo]];
+  [%foo (object end [@foo])];
```
Comment (jberdine) [inline test/passing/js_source.ml.ref]: Question: Am I correct that the output before still parses correctly, or is the sanity checking not tight enough?

**Comment by gpetiot** [comment]
I think I got them all this time.
