### PR TITLE
Fix break struct natural

### LINKED ISSUE #376: Issue with "break-struct=natural"
Using `break-struct=natural`, the following code:

```ocaml
module Hash = struct
  include Hash
  module type S = S.HASH
end
```

is reformated as follows:

```ocaml
module Hash = struct include Hash

                     module type S = S.HASH end
```

which looks a bit strange to me.

### PR DESCRIPTION
**Pull request by gpetiot**
Should fix #376

### CODE REVIEW

**Comment by gpetiot** [comment]
@samoht is this the output you expected?

File: test/passing/break_struct.ml.ref [hunk 1]
```diff
@@ -1,3 +1,35 @@
 [@@@ocamlformat "break-struct=natural"]
 
 module M = X (Y) (struct let x = k end)
+
+module Hash = struct include Hash module type S = S.HASH end
+
+module Hash = struct
+  include Hash include Hash module type S = S.HASH module type S = S.HASH
```
Comment (samoht) [inline test/passing/break_struct.ml.ref]: why does it not break here?

File: test/passing/break_struct.ml.ref [hunk 2]
```diff
@@ -1,3 +1,35 @@
...
+end
+
+module Hash = struct
+  include Hash
+  include Hash
+  include Hash
+
+  module type S = S.HASH
+
```
Comment (samoht) [inline test/passing/break_struct.ml.ref]: why does it adds a newline between the `module type S` sentences?

**Comment by jberdine** [comment]
Probably related to @samoht's nits, below is a case that regresses with this PR:
```
module Vector = struct
  include Vector

  let pp sep pp_elt fs v = List.pp sep pp_elt fs (to_list v)
end
```
should not format to
```
module Vector = struct
  include Vector let pp sep pp_elt fs v = List.pp sep pp_elt fs (to_list v)
end
```

File: test/passing/break_struct.ml.ref (hunk 2 above)
Comment (gpetiot) [reply test/passing/break_struct.ml.ref]: This is due to the grouping (similar simple items are grouped together) that is done for structure items. Otherwise, everything else seems to be formatted alright

**Comment by gpetiot** [comment]
The new output should be better, what do you all think?

File: src/import/Import.ml [hunk 3]
```diff
@@ -18,8 +18,8 @@ include (
 
       include
         module type of Base
-        (* [Filename], [Format], [Scanf] are all deprecated in [Base], erase
-           them and use the ones from the stdlib. *)
+          (* [Filename], [Format], [Scanf] are all deprecated in [Base],
+             erase them and use the ones from the stdlib. *)
```
Comment (gpetiot) [inline src/import/Import.ml]: The new indentation looks more natural to me with the new boxing

Comment (jberdine) [reply src/import/Import.ml]: I'm not sure I agree, but it's not a big deal, and the rest of the effect of this patch is a significant improvement.
