### PR TITLE
Fix attribute when break-infix-before-func=false

### LINKED ISSUE #915: Bug with break-infix-before-func=false and warning annotation
With both OCamlFormat 0.10 and 5f99201, and the following configuration:

```
break-infix-before-func=false
```

Input file:

```ocaml
let _ =
  foo >>= function [@warning "-4"]
    | A -> false
    | B -> true
```

Output:

```
ocamlformat: Cannot process "bug.ml".
  Please report this bug at https://github.com/ocaml-ppx/ocamlformat/issues.
  BUG: ast changed.
```

It works if you remove either the infix operator or the annotation.

### PR DESCRIPTION
**Pull request by gpetiot**
Fix #915 
No diff with test_branch.

### CODE REVIEW

File: test/passing/infix_bind.ml [hunk 1]
```diff
@@ -181,3 +181,28 @@ let foo =
...
+  foo >>= fun [@warning "-4"] x ->
+  fooooooooooooooooooooooo
+
+let _ =
+  foo >>= fun [@warning "-4"] x y ->
+  fooooooooooooooooooooooo fooooooooooooooooooooooo fooooooooooooooooooooooo
+    fooooooooooooooooooooooo
+
+let _ =
+  foo >>= function(* foo before *) [@warning "-4"] (* foo after *)
```
Comment (Julow) [inline test/passing/infix_bind.ml]: Shouldn't be a space after `function` ?

File: test/passing/infix_bind.ml [hunk 2]
```diff
@@ -181,3 +181,28 @@ let foo =
...
+
+let _ = foo >>= function[@warning "-4"] A -> false | B -> true
+
+let _ =
+  foo >>= function[@warning "-4"]
+  | Afoooooooooooooooooo fooooooooo -> false
+  | Bfoooooooooooooooooooooo fooooooooo -> true
+
+let _ =
+  foo >>= fun [@warning "-4"] x ->
```
Comment (Julow) [inline test/passing/infix_bind.ml]: Is there a reason to add a space before the attribute on `fun` but not on `function` ?

File: test/passing/infix_bind.ml (hunk 1 above)
Comment (gpetiot) [reply test/passing/infix_bind.ml]: It wouldn't hurt to have a space after the keyword, but there is also no space when `break-infix-before-func=true` so I was thinking at looking at that in another PR (didn't find a quick way to find that just now).
