### PR TITLE
Correctly format chunks of file in presence of enable/disable floating attributes

### LINKED ISSUE #1545: Docstring parsing fails with [@@@ocamlformat "disable"]
**How to Reproduce**
Running
```sh
ocamlformat foo.ml --inplace
```
on this file
```ml
[@@@ocamlformat "disable"]

(** hello *)
let foo = 42
```
produces this error
```
ocamlformat: Cannot process "foo.ml".
  Please report this bug at https://github.com/ocaml-ppx/ocamlformat/issues.
  BUG: doc comments changed.
File "_none_", line 1:
Error: Formatting of (** hello *) is unstable (e.g. parses as a list or not depending on the margin), please tighten up this comment in the source or disable the formatting using the option --no-parse-docstrings.
```
when using ocamlformat `0.15.0`.

### PR DESCRIPTION
**Pull request by gpetiot**
Fix #1545

### CODE REVIEW

File: lib/Fmt_ast.ml [hunk 1]
```diff
@@ -4412,15 +4412,112 @@ let fmt_repl_file c _ itms =
...
   let c = {source; cmts; conf; debug; fmt_code} in
   match (fragment, itms) with
   | Structure, [] | Signature, [] | Use_file, [] ->
       Cmts.fmt_after ~pro:noop c Location.none
-  | Structure, l -> fmt_structure c ctx l
-  | Signature, l -> fmt_signature c ctx l
-  | Use_file, l -> fmt_toplevel c ctx l
+  | Structure, l ->
+      split_format_chunks c ctx l
+        ~is_disabling:
```
Comment (Julow) [inline lib/Fmt_ast.ml:4469]: The repeated `is_disabling` and `is_enabling` could be implemented within `split_format_chunks` if provided a shorter `a -> attrs * loc` function for every kinds.

File: lib/Fmt_ast.ml [hunk 2]
```diff
@@ -4412,15 +4412,112 @@ let fmt_repl_file c _ itms =
...
+            ref_c := update !ref_c true ;
+            false
+        | k, _ when Option.is_some (is_enabling !ref_c k) ->
+            ref_c := update !ref_c false ;
+            false
+        | _ -> false )
+  in
+  List.foldi groups ~init:(c, noop) ~f:(fun i (c, output) g ->
+      match g with
+      | k :: _ when Option.is_some (is_disabling c k) ->
```
Comment (Julow) [inline lib/Fmt_ast.ml:4445]: The disabled/enabled information could be stored in the group.

File: test/passing/tests/comments_around_disabled.ml [hunk 3]
```diff
@@ -1,7 +1,7 @@
-(* cmts *)
+(* cmts before *)
 
 [@@@ocamlformat "disable"]
 let () = ()
```
Comment (Julow) [inline test/passing/tests/comments_around_disabled.ml:4]: It would be better if this was something that is obviously not formatted. With a line break in the middle for example.

Comment (gpetiot) [reply test/passing/tests/comments_around_disabled.ml]: done

File: lib/Fmt_ast.ml (hunk 2 above)
Comment (gpetiot) [reply lib/Fmt_ast.ml]: done

File: lib/Fmt_ast.ml (hunk 1 above)
Comment (gpetiot) [reply lib/Fmt_ast.ml]: done

**Review by Julow — APPROVED** [review]
Looks good :)
