### PR TITLE
Preserve the syntax of infix set/get operators

### LINKED ISSUE #1500: String and array operator rewriting can change program semantics
Hi,

As of 0.15.0, OCamlformat decides whether to use `a.[i]` or `String.get a i` depending on the context (similarly for `String.set`, `Array.get` and `Array.set`). This works under the assumption that `a.[i]` is parsed as `String.get i`, so both constructs have the same semantics.

However, that's not always true. [If `Clflags.unsafe` is set, the operators are parsed as the unsafe variants](https://github.com/ocaml/ocaml/blob/5e15dd8eb5b3b5f0e66f9166d4de2bcee22aa57d/parsing/parser.mly#L243-L245), e.g. `String.unsafe_get a i`.

Consider the following program:

    let () = String.get "hello world" (-8) |> Char.code |> Printf.printf "%d\n"

Built with the following dune file:

```
(executable
 (name t)
 (flags :standard -unsafe))
```

When executed, it outputs an error:

    Fatal error: exception Invalid_argument("index out of bounds")

This is because `String.get` always does the check.

When reformatting the above program, it gets rewritten to:

    let () = "hello world".[-8] |> Char.code |> Printf.printf "%d\n"

When executed, it outputs `252`, the value of `String_tag` (this is just to show that the program is now unsafe; it could of course cause kind of memory error later in the program).

So, what should we do? Given that the two constructions do not always have the same semantics depending on how the file is compiled, I think that the only valid way to handle the situation is to preserve what can be found in the file.

### PR DESCRIPTION
**Pull request by gpetiot**
Fix #1500, no diff with test_branch.sh

### CODE REVIEW

**Comment by hhugo** [comment]
cc @ceastlund, this might also affect formatting of auto-generated files.

**Comment by ceastlund** [comment]
Thanks, @hhugo, but I'm less concerned about this one. I'm fine with `String.get` showing up in our code from time to time.

**Review by Julow — APPROVED** [review]
Looks good.

This only works as long as `Clflags.unsafe` isn't set by default in the compiler OCamlformat is compiled with.
Thought, the only change is that operators are changed to explicit calls to the unsafe functions.

File: lib/Ast.ml [hunk 1]
```diff
@@ -158,7 +158,8 @@ module Indexing_op = struct
     | Some (lhs :: args) -> (
       match ident with
       | {pexp_desc= Pexp_ident {txt= ident; loc}; pexp_attributes= []; _}
-        -> (
+      (* We only use the sugared form if it was already used in the source. *)
+        when loc.loc_ghost -> (
```
Comment (emillon) [inline lib/Ast.ml:162]: In what cases does `get_sugar_ident` returns None now?

Comment (Julow) [reply lib/Ast.ml:162]: In the case `ident` is not an indexing operator (`Array.get`, `.()`, etc..) or the number of argument is not right (if there is not enough or too many, it cannot be a "sugar" expression).

Comment (Julow) [reply lib/Ast.ml:162]: That didn't change. `get_sugar` changed however, it returns None in case of labelled arguments, attributes and now there is this new check.
