### PR TITLE
Fix type manifest formatting

### LINKED ISSUE #614: Strange formatting for type .. = ... = ...
When the “original” type has a long module path, the newlines & indentation are not that optimal:

```ocaml
type voting_period =
                    Tezos_client_alpha.Proto_alpha.Alpha_context.Voting_period
                    .kind =
  | Proposal
  | Testing_vote
  | Testing
  | Promotion_vote
```

### PR DESCRIPTION
**Pull request by gpetiot**
Fix #614

### CODE REVIEW

File: test/passing/types.ml [hunk 1]
```diff
@@ -50,3 +50,10 @@ val x :
     (* boooooom *)
     (** foooooooooooooooo foooooooooooooooooooooooo fooooooooooooooooooooooo
         fooooooooooooooooooo fooooooooooooooo*) ]
+
+type voting_period =
+  Tezos_client_alpha.Proto_alpha.Alpha_context.Voting_period.kind =
```
Comment (jberdine) [inline test/passing/types.ml]: I'm unsure if this is the best choice of indentation level. Aligning the type alias with the definition, where the `=` is all the way on the right, is possible misleading. What about increasing the indentation of the type alias, perhaps aligning with the beginning of the defined type name?

It would also be good to check what happens to docstrings and comments in these cases.

Comment (gpetiot) [reply test/passing/types.ml]: Fixed in my last commit.

File: test/passing/types.ml [hunk 2]
```diff
@@ -50,3 +50,19 @@ val x :
     (* boooooom *)
     (** foooooooooooooooo foooooooooooooooooooooooo fooooooooooooooooooooooo
         fooooooooooooooooooo fooooooooooooooo*) ]
+
+type voting_period =
+    Tezos_client_alpha.Proto_alpha.Alpha_context.Voting_period.kind =
+  | Proposal
+  | Testing_vote
```
Comment (jberdine) [inline test/passing/types.ml]: What do others think about the indentation of line 55 in this example? It seems that both 2 and 4 spaces cause misleading vertical alignment. Would 6 be too much? I'm thinking that this situation is probably rare enough that 6 would be ok.

Comment (gpetiot) [reply test/passing/types.ml]: I agree with your suggestion, I updated the code.

**Comment by gpetiot** [comment]
> Looking at the diff from test_branch, I saw:
> (...)
> Both before and after this PR the type encroaches into the margin, but it's worse after this PR.

If the margin was not respected before it looks like a `Format` bug that should be addressed in another PR.

**Comment by gpetiot** [comment]
So do we merge it for 0.9 or do we postpone it for the next release? (not urgent if it's not ready right now)

**Comment by gpetiot** [comment]
The margin issue is now fixed, here is the new test_branch diff:

```ocaml
diff --git a/infer/src/IR/ProcnameDispatcher.ml b/infer/src/IR/ProcnameDispatcher.ml
index 389cae900..079d0c48b 100644
--- a/infer/src/IR/ProcnameDispatcher.ml
+++ b/infer/src/IR/ProcnameDispatcher.ml
@@ -82,8 +82,13 @@ type ( 'f_in
       -> ('f_out * 'captured_types_out capt * Typ.template_arg list) option
   ; add_marker: 'markers_in -> 'markers_out }
 
-type ('context, 'f_in, 'f_out, 'captured_types, 'markers_in, 'markers_out, 'list_constraint) templ_matcher
-   =
+type ( 'context
+     , 'f_in
+     , 'f_out
+     , 'captured_types
+     , 'markers_in
+     , 'markers_out
+     , 'list_constraint ) templ_matcher =
   { on_objc_cpp:
          'context
       -> 'f_in
diff --git a/infer/src/IR/ProcnameDispatcher.mli b/infer/src/IR/ProcnameDispatcher.mli
index d2cdb4d80..e2b4c6ab5 100644
--- a/infer/src/IR/ProcnameDispatcher.mli
+++ b/infer/src/IR/ProcnameDispatcher.mli
@@ -35,7 +35,13 @@ type ( 'f_in
      , 'markers_out
      , 'list_constraint ) template_arg
 
-type ('context, 'f_in, 'f_out, 'captured_types, 'markers_in, 'markers_out, 'list_constraint) templ_matcher
+type ( 'context
+     , 'f_in
+     , 'f_out
+     , 'captured_types
+     , 'markers_in
+     , 'markers_out
+     , 'list_constraint ) templ_matcher

diff --git a/otherlibs/threads/stdlib.ml b/otherlibs/threads/stdlib.ml
index 4e5a9c940..6329c3bff 100644
--- a/otherlibs/threads/stdlib.ml
+++ b/otherlibs/threads/stdlib.ml
@@ -738,13 +738,7 @@ end
 (* Formats *)
 
 type ('a, 'b, 'c, 'd, 'e, 'f) format6 =
-                                       ( 'a
-                                       , 'b
-                                       , 'c
-                                       , 'd
-                                       , 'e
-                                       , 'f )
-                                       CamlinternalFormatBasics.format6 =
+      ('a, 'b, 'c, 'd, 'e, 'f) CamlinternalFormatBasics.format6 =
   | Format of ('a, 'b, 'c, 'd, 'e, 'f) CamlinternalFormatBasics.fmt * string
 
 type ('a, 'b, 'c, 'd) format4 = ('a, 'b, 'c, 'c, 'c, 'd) format6
diff --git a/stdlib/stdlib.ml b/stdlib/stdlib.ml
index ea9382acf..2254ab987 100644
--- a/stdlib/stdlib.ml
+++ b/stdlib/stdlib.ml
@@ -667,13 +667,7 @@ end
 (* Formats *)
 
 type ('a, 'b, 'c, 'd, 'e, 'f) format6 =
-                                       ( 'a
-                                       , 'b
-                                       , 'c
-                                       , 'd
-                                       , 'e
-                                       , 'f )
-                                       CamlinternalFormatBasics.format6 =
+      ('a, 'b, 'c, 'd, 'e, 'f) CamlinternalFormatBasics.format6 =
   | Format of ('a, 'b, 'c, 'd, 'e, 'f) CamlinternalFormatBasics.fmt * string
```

File: test/passing/types.ml [hunk 3]
```diff
@@ -50,3 +50,31 @@ val x :
...
+      (* foooooooooooo *)
+      (* foooooooooo ooooooooooooooooo ooooooooooooo *)
+      Tezos_client_alpha.Proto_alpha.Alpha_context.Voting_period.kind
+      (* fooooooooooooooo oooooooooooooooooooo ooooooooooooooooooooo *)
+      (* fooooo *) =
+  (* foooooooooo *)
+  | Proposal
+  | Testing_vote  (** fooooooooooo *)
+
+type ( 'context
```
Comment (Julow) [inline test/passing/types.ml]: This is how it looks with manifest:

```
type ( 'context
     , 'f_in
     , 'f_out
     , 'captured_types
     , 'markers_in
     , 'markers_out
     , 'list_constraint ) templ_matcher =
      ( 'context
      , 'f_in
      , 'f_out
      , 'captured_types
      , 'markers_in
      , 'markers_out
      , 'list_constraint )
      templ_matcher =
  { on_objc_cpp: 'context -> 'f_in
  ; on_objc_cpp: 'context -> 'f_in
  ; on_objc_cpp: 'context -> 'f_in
  ; on_objc_cpp: 'context -> 'f_in }
```

the `templ_matcher` could fit on the line above

File: src/Fmt_ast.ml [hunk 4]
```diff
@@ -2745,14 +2743,16 @@ and fmt_type_declaration c ?(pre = "") ?(suf = ("" : _ format)) ?(brk = suf)
...
+  let maybe_box = if List.is_empty ptype_params then Fn.id else hvbox 0 in
   Cmts.fmt c loc @@ Cmts.fmt c ptype_loc
   @@ hvbox 0
        ( fmt_docstring c ~epi:(fmt "@\n") doc
        $ hvbox 0
            ( hvbox 2
-               ( str pre
-               $ fmt_tydcl_params c ctx ptype_params
-               $ (match fmt_name with Some pp -> pp | None -> str txt)
+               ( open_hvbox 2 $ str pre
```
Comment (Julow) [inline src/Fmt_ast.ml]: This open should pair with the closes in `fmt_manifest_kind`? I don't like this.
I suggest you pass this formatting to `fmt_manifest_kind` and let it handle boxes, without explicit open/close.

File: src/Fmt_ast.ml [hunk 5]
```diff
@@ -2667,30 +2666,32 @@ and fmt_type_declaration c ?(pre = "") ?(suf = ("" : _ format)) ?(brk = suf)
   in
   update_config_maybe_disabled c ptype_loc ptype_attributes
   @@ fun c ->
+  let break_before_manifest_kind =
```
Comment (Julow) [inline src/Fmt_ast.ml]: You could move this inside `fmt_manifest`

File: test/passing/types.ml [hunk 6]
```diff
@@ -50,3 +50,31 @@ val x :
...
+     , 'f_in
+     , 'f_out
+     , 'captured_types
+     , 'markers_in
+     , 'markers_out
+     , 'list_constraint ) templ_matcher =
+  { on_objc_cpp: 'context -> 'f_in
+  ; on_objc_cpp: 'context -> 'f_in
+  ; on_objc_cpp: 'context -> 'f_in
+  ; on_objc_cpp: 'context -> 'f_in }
```
Comment (Julow) [inline test/passing/types.ml]: Could you add this case with type extension because it does not share ast and formatting logic:

```
type ( 'context
     , 'f_in
     , 'f_out
     , 'captured_types
     , 'markers_in
     , 'markers_out
     , 'list_constraint ) templ_matcher +=
  | On_objc_cpp : 'context -> 'f_in
  | On_objc_cpp : 'context -> 'f_in
  | On_objc_cpp : 'context -> 'f_in
  | On_objc_cpp : 'context -> 'f_in
```

File: test/passing/types.ml (hunk 3 above)
Comment (gpetiot) [reply test/passing/types.ml]: Looks like currently having the identifier on the next line is expected so I will use this behavior everywhere instead.

File: src/Fmt_ast.ml (hunk 5 above)
Comment (gpetiot) [reply src/Fmt_ast.ml]: done

File: test/passing/types.ml (hunk 6 above)
Comment (gpetiot) [reply test/passing/types.ml]: done

File: src/Fmt_ast.ml (hunk 4 above)
Comment (gpetiot) [reply src/Fmt_ast.ml]: done
