### PR TITLE
Fix parsing of invalid file wrt original source handling

### LINKED ISSUE #1534: Bug: formatting invalid files can fail because of incoherent locations.
**Describe the bug**

When recovering an invalid file, we generate a new valid source but feed the original source to `Source.create`.
Attempting to inspect the source will either return random information or fail.

Note that feeding the recovered source to `Source.create` should work ~but will result in invalid locations for warnings~. 

**How to Reproduce**
```sh
cat y.ml
```
```ocaml
let x = 1 +
;;

let x = "\064"
```
```sh
$ ocamlformat y.ml --enable-outside-detected-project --format-invalid-files=auto
Warning: /home/hheuzard/y.ml is invalid, recovering.
ocamlformat: Cannot process "/home/hheuzard/y.ml".
  Please report this bug at https://github.com/ocaml-ppx/ocamlformat/issues.
  BUG: unhandled exception. Use [--debug] for details.
```

### PR DESCRIPTION
**Pull request by hhugo**
fix #1534
There are multiple parts here:
- move all the parsing + lexing logic in the same place: `Parse_with_comments.ml`
- tie `ast` and `Source.t` together in `Parse_with_comments`, we want location in the ast and the source to be coherent.
- output `;;` after an invalid fragment if it was present in the source

### CODE REVIEW

File: test/passing/format_invalid_files_with_locations.ml.opts [hunk 1]
```diff
@@ -0,0 +1 @@
+--format-invalid-files=auto -n 3
```
Comment (gpetiot) [inline test/passing/format_invalid_files_with_locations.ml.opts:1]: We usually use `--max-iter` instead of `-n` we should keep it that way to grep everything in one go

**Review by gpetiot — COMMENTED** [review]
Looks good to me, thanks! I appreciate the simplifications in all the parse_with_comments code.
Maybe wait until 0.16.0 is released to merge this one though, since we are freezing master now for the release (cc @emillon )

**Comment by hhugo** [comment]
will wait for 0.17

**Comment by hhugo** [comment]
@emillon, Can you update `CHANGES.md` with the 0.16 release ? I'm rebase and merge this PR then.
