### PR TITLE
Fix: break multiline comments

### LINKED ISSUE #912: ocamlformat mishandles multiple-line comments between named function arguments
```
let g = f ~x (* this is a multiple-line-spanning
                comment *) ~y
```

This formats without a closing `;;` and with `~y` on the same line as the end of the comment; clearly ocamlformat is treating this comment like it is part of a single line.

### PR DESCRIPTION
**Pull request by gpetiot**
Fix #912 and #1100, something similar could be done for docstrings to tackle #1043 

The diff of test_branch.sh looks good.

This new behavior is only triggered when `wrap-comments=false` and when the first line of the comment is not empty (we don't want to indent the following lines of the comment if the first one is empty).

### CODE REVIEW

File: src/Cmts.ml [hunk 1]
```diff
@@ -490,10 +490,35 @@ let fmt_cmt (conf : Conf.t) ~fmt_code (cmt : Cmt.t) =
...
             | _, Some _ -> str line $ fmt "@,*") )
   in
-  let fmt_non_code (cmt : Cmt.t) =
+  let fmt_unwrapped_cmt ({txt= s; loc} : Cmt.t) =
+    let lines = String.split_lines s in
+    let first_line_empty =
+      List.length lines > 0 && String.is_empty (List.hd_exn lines)
+    in
+    let begins_line = Source.begins_line t.source loc ~ignore_spaces:false in
+    if String.contains s '\n' && (not begins_line) && not first_line_empty
```
Comment (Julow) [inline src/Cmts.ml]: What is the reason for this condition ?

File: src/Cmts.ml [hunk 2]
```diff
@@ -490,10 +490,35 @@ let fmt_cmt (conf : Conf.t) ~fmt_code (cmt : Cmt.t) =
...
+    then
+      let b_space = String.length s > 0 && Char.equal s.[0] ' ' in
+      let e_space =
+        String.length s > 0 && Char.equal s.[String.length s - 1] ' '
```
Comment (Julow) [inline src/Cmts.ml]:
```suggestion
        String.length s > 1 && Char.equal s.[String.length s - 1] ' '
```
To avoid picking the same character as for `b_space` ?

File: src/Cmts.ml (hunk 1 above)
Comment (gpetiot) [reply src/Cmts.ml]: - the first one is obviously because we only want to do the special treatment when there are `\n` inside (not using the box and so on)
- the second one: breaking comments that begin at the beginning of the line have no incidence of the associated code (the issue was that the code was not broken when the comment was broken, but if the comment is at column 0 it is very likely that the associated code is already either a one-liner or broken), so no different treatment to avoid a huge diff
- the last one because if the first line of a comment is empty we don't want to indent the following lines relatively to this line

File: src/Cmts.ml (hunk 2 above)
Comment (gpetiot) [reply src/Cmts.ml]: I agree, but this code (and more) could be simplified since we suppose `s` contains an `\n` anyway (not a fan of hidden assumptions though)

Comment (Julow) [reply src/Cmts.ml]: It's not really an hidden assumption, the `if` is 2 lines above !
I agree this constant deserves a comment.

File: src/Cmts.ml (hunk 1 above)
Comment (Julow) [reply src/Cmts.ml]: Thanks, that makes sense.

File: src/Cmts.ml [hunk 3]
```diff
@@ -490,10 +490,35 @@ let fmt_cmt (conf : Conf.t) ~fmt_code (cmt : Cmt.t) =
...
+        String.length s > 1 && Char.equal s.[String.length s - 1] ' '
+      in
+      let fmt_line ~first ~last s =
+        if String.(is_empty (strip s)) then
+          if last then if first then str s else fmt "@;<1000 -2>"
+          else str "\n"
+        else
+          fmt_if (not first) "@;<1000 0>"
+          $ fmt_if b_space " "
+          $ str (String.strip s)
```
Comment (Julow) [inline src/Cmts.ml]: You are stripping the same string twice.

**Comment by gpetiot** [comment]
@ceastlund does the new behavior proposed in this PR sound good to you?

**Comment by ceastlund** [comment]
Where should I look to understand the new behavior?

**Comment by gpetiot** [comment]
As I wrote in the initial message, the new behavior (breaking a comment on newlines `\n`) is only triggered when `wrap-comments=false` (it's the case when using the `janestreet` profile) and when the first line of the comment is not empty (we don't want to indent the following lines of the comment if the first one is empty).

So if the first line of a comment is empty, the comment is not modified by this PR, meaning you may want to remove to remove the empty lines at the beginning of comments to have them break properly.

**Comment by ceastlund** [comment]
Okay, yes, between that and reading the changes to JS test files, this change looks good. Thanks very much!
