### PR TITLE
Fix typedecl attribute

### LINKED ISSUE #578: Attribute ignored on type declaration
The attribute is ignored in:

```ocaml
type t = { a : int (* Comment *); b : int (* Comment *) }
[@@ocamlformat "type-decl=sparse"]
```

and the code is formatted in compact mode

Global attribute (`[@@@ocamlformat "type-decl=sparse"]`) still works

### PR DESCRIPTION
**Pull request by gpetiot**
Fix #578 
tools/test_branch.sh did not show any regression.

### CODE REVIEW

File: test/passing/comments_in_record.ml.ref [hunk 1]
```diff
@@ -12,7 +12,9 @@ type t =
 
 type t = {a: int (* Comment *); b: int (* Comment *)}
 
-type t = {a: int (* Comment *); b: int (* Comment *)}
+type t =
+  { a: int (* Comment *)
+  ; b: int (* Comment *) }
 [@@ocamlformat "type-decl=sparse"]
 
 (* TODO: delete this (module X) when the type t above is correctly formatted
```
Comment (Julow) [inline test/passing/comments_in_record.ml.ref]: You can delete this
