### PR TITLE
Colon instead of arrow before type for GADT constructors with no arguments

### LINKED ISSUE #39: GADT constructors with no arguments
`type t = A : t` is wrongly translated to `type t = A -> t`
(version 729c358, currently latest)

### PR DESCRIPTION
**Pull request by mbouaziz**
Fixes #39

Tested on `type t = A : t` as well as more complex GADTs, which will make it to `infer.git` sooner or later.

### CODE REVIEW

File: src/Fmt_ast.ml [hunk 1]
```diff
@@ -1395,7 +1395,10 @@ and fmt_constructor_arguments_result c ctx args res =
   let pre : _ format = if Option.is_none res then " of@ " else ": " in
   fmt_constructor_arguments c ctx pre args
   $ opt res (fun typ ->
-        fmt " " $ fmt "-> " $ fmt_core_type c (sub_typ ~ctx typ) )
+        let before_type : _ format =
+          match args with Pcstr_tuple [] -> ": " | _ -> "-> "
+        in
+        fmt " " $ fmt before_type $ fmt_core_type c (sub_typ ~ctx typ) )
```
Comment (jberdine) [inline src/Fmt_ast.ml]: Maybe move this to before `let pre` to keep the formatting combinator code clearer?

**Comment by mbouaziz** [comment]
Updated
