### PR TITLE
Fix indent match branches with cmts

### LINKED ISSUE #643: Weird indentation in match branches with comment
I'm sorry, I don't have a good inspiration for the title of this issue. Please feel free to change it to something clearer.

When the first line of a branch in a match has a comment and then a single line of code, the comment is placed on the line of the pattern and the line of code is aligned on the comment. It leads to a pretty surprising and inconsistent indentation.

Before: 

```ocaml
let rec loop items =
  match [] with
  | _ :: _ :: items ->
    (* a comment *)
    loop items
  | _ :: items ->
    (* another comment*)
    loop items
  | _ ->
    let a = 3 in
    a
```

After:

```ocaml
let rec loop items =
  match [] with
  | _ :: _ :: items -> (* a comment *)
                       loop items
  | _ :: items -> (* another comment*)
                  loop items
  | _ ->
    let a = 3 in
    a
```

ocamlformat version: b257f2d3eeaeea3cc395e5ef1d264fc9ad4611f2
configuration: default

### PR DESCRIPTION
**Pull request by gpetiot**
Fix #643 
test_branch exhibits that we fixed a lot of these cases:
```ocaml
--- a/ocamldoc/odoc_man.ml
+++ b/ocamldoc/odoc_man.ml
@@ -307,8 +307,9 @@ module Generator = struct
         | Odoc_info.Title (_, _, t) ->
             let txt = Odoc_info.string_of_text t in
             bp b ".SS %s\n" txt
-        | Odoc_info.Latex _ -> (* don't care about LaTeX stuff in HTML. *)
-                               ()
+        | Odoc_info.Latex _ ->
+            (* don't care about LaTeX stuff in HTML. *)
+            ()
         | Odoc_info.Link (_, t) -> self#man_of_text2 b t
         | Odoc_info.Ref (name, _, _) ->
             self#man_of_text_element b
@@ -1191,8 +1192,9 @@ module Generator = struct
                     self#man_of_module_type b (Name.father mt.mt_name) t ) ;
                 bs b "\n.sp\n" ;
                 self#man_of_module_type_body b mt
-            | Res_section _ -> (* normally, we cannot have modules here. *)
-                               ()
+            | Res_section _ ->
+                (* normally, we cannot have modules here. *)
+                ()
           in
           List.iter f l ;
           Buffer.output_buffer chanout b ;
diff --git a/ocamldoc/odoc_merge.ml b/ocamldoc/odoc_merge.ml
index f6ef8fca5..aa222f26f 100644
--- a/ocamldoc/odoc_merge.ml
+++ b/ocamldoc/odoc_merge.ml
@@ -847,8 +847,9 @@ let merge merge_options modules_list =
           List.partition (fun m2 -> m.m_name = m2.m_name) q
         in
         match l_same with
-        | [] -> (* no other module to merge with *)
-                m :: iter l_others
+        | [] ->
+            (* no other module to merge with *)
+            m :: iter l_others
         | [m2] -> (
             (* we can merge m with m2 if there is an implementation
                 and an interface.*)
```

### CODE REVIEW

File: test/passing/break_cases_all.ml [hunk 1]
```diff
@@ -132,3 +132,15 @@ let () =
   | foooooo
```
Comment (Julow) [inline test/passing/break_cases_all.ml]: The symlinks and .ref/.opts trick is worth setting up here I think.

**Comment by gpetiot** [comment]
> Looks good to me. The `eol` parameter is a bit obscure.
> 
> Maybe unrelated but testing with if statement, is it intended:
> 
> ```
> let rec loop items =
>   (* a comment *)
>   if abcd efghij klmnop qrstu then (* a comment *)
>     loop items
>   else if blablablablalblabla then (* another comment*)
>     loop items
>   else
>     let a = 3 in
>     a
> ```

Yes keeping the comment at the end of the line is intended, see the discussion in #603

File: test/passing/break_cases_all.ml (hunk 1 above)
Comment (gpetiot) [reply test/passing/break_cases_all.ml]: done
