### PR TITLE
Fix formatting of comment with just a newline

### LINKED ISSUE #1268: Bug: index out of bounds when a comment contains just a newline
Hi,

The following program crashes ocamlformat with an index out of bounds exception:

    (*
    *)

(bytes: 0x28 0x2a 0x0a 0x2a 0x29 0x0a)

### PR DESCRIPTION
**Pull request by emillon**
This reworks a bit the Cmts / `fill_text` interface to fix #1268. In particular the existing empty string branch seems to be dead since `(* *)` produces a space character and `(**)` is parsed as a doc comment.

### CODE REVIEW

File: lib/Cmt.ml [hunk 1]
```diff
@@ -134,7 +134,7 @@ let fmt cmt src ~wrap:wrap_comments ~fmt_code =
           fmt_asterisk_prefixed_lines asterisk_prefixed_lines
     else
       match split_asterisk_prefixed cmt with
-      | [""] -> str "(* *)"
```
Comment (Julow) [inline lib/Cmt.ml]: Should we keep an assert here ?
I don't like that but the `asterisk_prefixed_lines` can't handle `[""]`, it would format to `(**)`, which would parse as a documentation comment.

Comment (Julow) [reply lib/Cmt.ml]: The `[]` cannot work too.
