### PR TITLE
Fix newlines and indentation in toplevel extension points

### LINKED ISSUE #1053: Bug: newlines in string literals in toplevel extension points are not considered for line breaking
**Describe the bug**
Below, the `%expect` has no newline before `{|`, but `%%expect` does put a newline before `{|`. The newline is unnecessary.
```
;;
[%expect {|
___________________________________________________________
|}]

[%%expect
  {|
___________________________________________________________
|}]
```

**How to Reproduce**
I get the above formatting using ocamlformat built from b28bb024fe633fe253b0b5e21fc55d877c1f8ac7 using `--profile=janestreet`.

### PR DESCRIPTION
**Pull request by gpetiot**
Fix #1053 
The linebreaks were incorrect, also we can be more precise in the box structure (no use for `fits` for now), and the option `stritem_extension_indent` should be taken into account to indent the payload of attributes, except for toplevel items. Also more consistency between structure and signature items.

No diff with test_branch for the default, the janestreet and the conventional profiles.

### CODE REVIEW

File: src/Fmt_ast.ml [hunk 1]
```diff
@@ -562,24 +562,14 @@ let sequence_blank_line c xe1 xe2 =
...
-
 let rec fmt_extension c ctx key (ext, pld) =
   match (pld, ctx) with
   | ( PStr [({pstr_desc= Pstr_value _ | Pstr_type _; _} as si)]
     , (Pld _ | Str _ | Top) ) ->
       fmt_structure_item c ~last:true ~ext (sub_str ~ctx si)
   | PSig [({psig_desc= Psig_type _; _} as si)], (Pld _ | Sig _ | Top) ->
       fmt_signature_item c ~ext (sub_sig ~ctx si)
-  | _ ->
-      let fits = fits c pld ~f:(fmt_payload c (Pld pld)) in
```
Comment (Julow) [inline src/Fmt_ast.ml]: It's great that we can get rid of that.
