### PR TITLE
Fix weird parens break

### LINKED ISSUE #706: Weird break for parens
```
$ echo "let _ = List.map rows ~f:(fun row -> Or_error.try_with (fun () -> fffffffffffffffffffffffff row))" | _build/dev/src/ocamlformat.exe --name a.ml --profile janestreet  -
let _ =
  List.map rows ~f:(fun row -> Or_error.try_with (fun () -> fffffffffffffffffffffffff row)
  )
;;
```

### PR DESCRIPTION
**Pull request by gpetiot**
Fix #706 
The diff of test_branch looks good.

with the janestreet profile:
```ocaml
diff --git a/src/Translation_unit.ml b/src/Translation_unit.ml
index 7b3d6eb..d5d31da 100644
--- a/src/Translation_unit.ml
+++ b/src/Translation_unit.ml
@@ -416,8 +416,8 @@ let format xunit (conf : Conf.t) ?output_file ~input_name ~source ~parsed () =
               ; "old ast", Option.map old_ast ~f:String.sexp_of_t
               ; "new ast", Option.map new_ast ~f:String.sexp_of_t
               ]
-              |> List.filter_map ~f:(fun (s, f_opt) -> Option.map f_opt ~f:(fun f -> s, f)
-                 )
+              |> List.filter_map ~f:(fun (s, f_opt) ->
+                     Option.map f_opt ~f:(fun f -> s, f))
             in
             internal_error `Comment args));
         (* Too many iteration ? *)
diff --git a/ppx/ppx_js/lib_internal/ppx_js_internal.ml b/ppx/ppx_js/lib_internal/ppx_js_internal.ml
index ba95ef038..fd8cd040c 100644
--- a/ppx/ppx_js/lib_internal/ppx_js_internal.ml
+++ b/ppx/ppx_js/lib_internal/ppx_js_internal.ml
@@ -214,7 +214,8 @@ let invoker ?(extra_types = []) uplift downlift body arguments =
      {[ fun (type res t0 t1 ..) arg1 arg2 -> e ]}
   *)
   let local_types =
-    make_str res :: List.map (extra_types @ arguments) ~f:(fun x -> make_str (Arg.name x))
+    make_str res
+    :: List.map (extra_types @ arguments) ~f:(fun x -> make_str (Arg.name x))
   in
   let result = List.fold_right local_types ~init:invoker ~f:Exp.newtype in
   default_loc := default_loc';
diff --git a/debugger/command_line.ml b/debugger/command_line.ml
index 88c735fd1..752e69c8c 100644
--- a/debugger/command_line.ml
+++ b/debugger/command_line.ml
@@ -107,7 +107,9 @@ let matching_elements list name instr =
     !list
 ;;
 
-let all_matching_instructions = matching_elements instruction_list (fun i -> i.instr_name)
+let all_matching_instructions =
+  matching_elements instruction_list (fun i -> i.instr_name)
+;;
 
 (* itz 04-21-96 don't do priority completion in emacs mode *)
 (* XL 25-02-97 why? I find it very confusing. *)
diff --git a/stdlib/camlinternalOO.ml b/stdlib/camlinternalOO.ml
index 305f658d1..6f6ef9a12 100644
--- a/stdlib/camlinternalOO.ml
+++ b/stdlib/camlinternalOO.ml
@@ -564,7 +564,10 @@ let app_env_const f e n x =
 ;;
 
 let meth_app_const n x = ret (fun obj -> (sendself obj n : _ -> _) x)
-let meth_app_var n m = ret (fun obj -> (sendself obj n : _ -> _) (Array.unsafe_get obj m))
+
+let meth_app_var n m =
+  ret (fun obj -> (sendself obj n : _ -> _) (Array.unsafe_get obj m))
+;;
 
 let meth_app_env n e m =
   ret (fun obj ->
diff --git a/testsuite/tests/typing-poly/poly.ml b/testsuite/tests/typing-poly/poly.ml
index eb6494c12..8cdaeabb4 100644
--- a/testsuite/tests/typing-poly/poly.ml
+++ b/testsuite/tests/typing-poly/poly.ml
@@ -959,7 +959,10 @@ class ['a] olist l =
 
 let sum (l : 'a #olist) = l#fold ~f:(fun x acc -> x + acc) ~init:0
 let count (l : 'a #olist) = l#fold ~f:(fun _ acc -> acc + 1) ~init:0
-let append (l : 'a #olist) (l' : 'b #olist) = l#fold ~init:l' ~f:(fun x acc -> acc#cons x)
+
+let append (l : 'a #olist) (l' : 'b #olist) =
+  l#fold ~init:l' ~f:(fun x acc -> acc#cons x)
+;;
```

### CODE REVIEW

File: src/Fmt_ast.ml [hunk 1]
```diff
@@ -1529,10 +1530,9 @@ and fmt_expression c ?(box = true) ?pro ?epi ?eol ?parens ?(indent_wrap = 0)
                              | _ -> None )
                            xbody )
                    $ fmt_or_k c.conf.indicate_multiline_delimiters
-                       (fmt_or_k
-                          (Location.is_single_line pexp_loc c.conf.margin)
-                          (fmt ")") (fits_breaks ")" "@ )"))
-                       (fits_breaks ")" "@,)") )
+                       (fmt_or_k fit (fmt ")")
+                          (fits_breaks ~force_fit_if:fit ")" "@ )"))
```
Comment (Julow) [inline src/Fmt_ast.ml]: Is `fits_breaks` necessary if we have `fit` ?

Comment (gpetiot) [reply src/Fmt_ast.ml]: Yes, any other thing I tried just caused more regressions (I didn't find a way to get rid of the `Location.is_single_line` either).

Comment (Julow) [reply src/Fmt_ast.ml]: I have no regressions with 
```patch
--- a/src/Fmt_ast.ml
+++ b/src/Fmt_ast.ml
@@ -1530,9 +1530,8 @@ and fmt_expression c ?(box = true) ?pro ?epi ?eol ?parens ?(indent_wrap = 0)
                              | _ -> None )
                            xbody )
                    $ fmt_or_k c.conf.indicate_multiline_delimiters
-                       (fmt_or_k fit (fmt ")")
-                          (fits_breaks ~force_fit_if:fit ")" "@ )"))
-                       (fits_breaks ~force_fit_if:fit ")" "@,)") )
+                       (fmt_or_k fit (fmt ")") (fmt_or fit ")" "@ )"))
+                       (fmt_or fit ")" "@,)") )
                $ fmt_atrs ))
       | ( lbl
         , ( { pexp_desc= Pexp_function [{pc_lhs; pc_guard= None; pc_rhs}]
```

Comment (gpetiot) [reply src/Fmt_ast.ml]: With this change I get the following diff:

```ocaml
diff --git a/src/Ast.ml b/src/Ast.ml
index 0031f7f..8b0ef74 100644
--- a/src/Ast.ml
+++ b/src/Ast.ml
@@ -805,8 +805,7 @@ end = struct
               || loop e
           | Pcf_method (_, _, Cfk_concrete _) -> false
           | Pcf_constraint (t1, t2) -> t1 == typ || t2 == typ
-          | Pcf_initializer _ | Pcf_attribute _ | Pcf_extension _ -> false
-      )
+          | Pcf_initializer _ | Pcf_attribute _ | Pcf_extension _ -> false )
     in
     let check_class_type l =
       List.exists l ~f:(fun {pci_expr= {pcty_desc}; pci_params} ->
diff --git a/src/Conf.ml b/src/Conf.ml
index 2f218be..d7da1a0 100644
--- a/src/Conf.ml
+++ b/src/Conf.ml
@@ -1840,8 +1840,7 @@ let action =
     Inplace
       (List.map !inputs ~f:(fun file ->
            let name = Option.value !name ~default:file in
-           {kind= kind_of file; name; file; conf= build_config ~file:name}
-       ))
+           {kind= kind_of file; name; file; conf= build_config ~file:name} ))
   else if !check then
     Check
       (List.map !inputs ~f:(fun file ->
diff --git a/src/Fmt_ast.ml b/src/Fmt_ast.ml
index 3bc41a8..d0ee0f1 100644
--- a/src/Fmt_ast.ml
+++ b/src/Fmt_ast.ml
@@ -2271,8 +2270,8 @@ and fmt_class_structure c ~ctx ?ext self_ fields =
         ( fmt "object"
         $ fmt_extension_suffix c ext
         $ opt self_ (fun self_ ->
-              fmt "@;" $ wrap "(" ")" (fmt_pattern c (sub_pat ~ctx self_))
-          ) )
+              fmt "@;" $ wrap "(" ")" (fmt_pattern c (sub_pat ~ctx self_)) )
+        )
     $ cmts_after_self
     $ ( match fields with
       | ({pcf_desc= Pcf_attribute a}, _) :: _
@@ -2318,8 +2317,8 @@ and fmt_class_signature c ~ctx ~parens ?ext self_ fields =
                $ fmt_extension_suffix c ext
                $ opt self_ (fun self_ ->
                      fmt "@;"
-                     $ wrap "(" ")" (fmt_core_type c (sub_typ ~ctx self_))
-                 ) )
+                     $ wrap "(" ")" (fmt_core_type c (sub_typ ~ctx self_)) )
+               )
            $ cmts_after_self
            $ ( match fields with
              | ({pctf_desc= Pctf_attribute a}, _) :: _
@@ -3793,8 +3792,7 @@ and fmt_structure c ctx itms =
         fmt_if_k (not first) (fmt_or break_struct "@\n" "@ ")
         $ maybe_disabled c itm.pstr_loc []
           @@ fun c ->
-          fmt_structure_item c ~last:(last && last_grp) (sub_str ~ctx itm)
-    )
+          fmt_structure_item c ~last:(last && last_grp) (sub_str ~ctx itm) )
```

Comment (Julow) [reply src/Fmt_ast.ml]: Sorry I forgot to test with `make fmt`.
