### PR TITLE
Fix nested parens with no break infix before func

### LINKED ISSUE #754: BUG: ast changed with Pexp_function inside match
The following snippet causes ocamlformat to emit the "BUG: ast changed." error:

```ocaml
match foo with
| 1 ->
  bar >>= (function | _ -> ())
| other -> ()

```

### PR DESCRIPTION
**Pull request by gpetiot**
Fix #754, I don't know if we should bother trying to handle `indicate-multiline-delimiters` since the beginning and the end of the function are not in the same box and we don't want to rely on `Location.is_single_line`?

No diff with test_branch with `break-infix-before-func=false`.

### CODE REVIEW

File: src/Fmt_ast.ml [hunk 1]
```diff
@@ -1443,17 +1443,19 @@ and fmt_expression c ?(box = true) ?pro ?epi ?eol ?parens ?(indent_wrap = 0)
       , [(Nolabel, l); (Nolabel, ({pexp_desc= Pexp_function cs} as r))] )
     when is_infix_id id && not c.conf.break_infix_before_func ->
       Cmts.relocate c.cmts ~src:pexp_loc ~before:loc ~after:loc ;
+      let xpc_rhs = sub_exp ~ctx r in
```
Comment (jberdine) [inline src/Fmt_ast.ml]: Here the `xpc_rhs` copypasta name doesn't really make sense, `xr` is likely better.

File: src/Fmt_ast.ml [hunk 2]
```diff
@@ -1443,17 +1443,19 @@ and fmt_expression c ?(box = true) ?pro ?epi ?eol ?parens ?(indent_wrap = 0)
...
+      let parens_fct = parenze_exp xpc_rhs in
```
Comment (jberdine) [inline src/Fmt_ast.ml]: Here it might be better to use `_r` instead of `_fct`. Or to rename `r`.

**Comment by gpetiot** [comment]
> I wonder if it might be better to assume the cases don't fit on a line instead, as I'd guess that more than half of the time that's what happens.

I agree, and the output looks good.
