### PR TITLE
Preserve position of comments attached to the last node of a subtree

### LINKED ISSUE #1662: Bug: undesirable comment placement after last match case
I can't find a good way to have a comment following the expression in the last match case. See example below.

Input:
```ocaml
let reserved_identifier (env : env) (x : CST.reserved_identifier) : ident =
  match x with
  | `Get tok -> identifier env tok (* "get" *)
  | `Set tok -> identifier env tok (* "set" *)
  | `Async tok -> identifier env tok (* "async" *)
  | `Static tok -> identifier env tok (* "static" *)
```

Output with ocamlformat version b04850d (May 21, 2021) with no options or with `--profile conventional`:
```ocaml
let reserved_identifier (env : env) (x : CST.reserved_identifier) : ident =
  match x with
  | `Get tok -> identifier env tok (* "get" *)
  | `Set tok -> identifier env tok (* "set" *)
  | `Async tok -> identifier env tok (* "async" *)
  | `Static tok -> identifier env tok
(* "static" *)
```

Expected output:
```ocaml
let reserved_identifier (env : env) (x : CST.reserved_identifier) : ident =
  match x with
  | `Get tok -> identifier env tok (* "get" *)
  | `Set tok -> identifier env tok (* "set" *)
  | `Async tok -> identifier env tok (* "async" *)
  | `Static tok -> identifier env tok (* "static" *)
```

A workaround is to place the comment before the expression. It looks like this and it's not that great:
```ocaml
let reserved_identifier (env : env) (x : CST.reserved_identifier) : ident =
  match x with
  | `Get tok -> (* "get" *) identifier env tok
  | `Set tok -> (* "set" *) identifier env tok
  | `Async tok -> (* "async" *) identifier env tok
  | `Static tok -> (* "static" *) identifier env tok
```

### LINKED ISSUE #1963: Bug: the comment that follows the last variant of a variant type is always formatted into a new line
Hi,

**Describe the bug**

In the latest OCamlformat (0.20.1), the comment of the last variant of a variant type is always placed into a new line after a code-formatting.

**How to Reproduce**

Here is an example with the file `foo.ml`.

``` ocaml
type bound =
  | PInf (* positive infinity *)
  | NInf (* negative infinity *)
  | Int64 of int64 (* integer 64 bit *)
  | EInt of eint (* integer in 2-exponential representation *)
  | BInt of bint (* big integer *)
```

When running `ocamlformat foo.ml` with the `default` profile (or any other profiles like `ocamlformat`, `janestreet`), the output is:

``` ocaml
type bound =
  | PInf (* positive infinity *)
  | NInf (* negative infinity *)
  | Int64 of int64 (* integer 64 bit *)
  | EInt of eint (* integer in 2-exponential representation *)
  | BInt of bint
(* big integer *)      
```

Here, the last comment `(* big integer *)` is unexpectedly put into a new line.

Can you double-check if this is a bug and can it be fixed?

Thank you!

### PR DESCRIPTION
**Pull request by gpetiot**
Fix #1662 
Fix #1963

Diff for the `janestreet` profile:

<details>

```diff
diff --git a/infer/src/topl/ToplAst.ml b/infer/src/topl/ToplAst.ml
index 3b606a25c..c964bc840 100644
--- a/infer/src/topl/ToplAst.ml
+++ b/infer/src/topl/ToplAst.ml
@@ -31,7 +31,6 @@ type predicate =
   | Value of (* bool *) value
 
 type condition = predicate list (* conjunction *)
-
 type assignment = register_name * variable_name
 
 (** a regular expression *)
diff --git a/src/dune_engine/rules.mli b/src/dune_engine/rules.mli
index dac6da247..95e18a85d 100644
--- a/src/dune_engine/rules.mli
+++ b/src/dune_engine/rules.mli
@@ -26,7 +26,7 @@ module Dir_rules : sig
 
            When passing [--force] to Dune, these are exactly the actions that
            will be re-executed. *)
-          Action of
+        Action of
           Rule.Anonymous_action.t Action_builder.t
 
     type t = { expansions : (Loc.t * item) Appendable_list.t } [@@unboxed]
diff --git a/src/dune_engine/scheduler.ml b/src/dune_engine/scheduler.ml
index 428a6ba56..e09e45d3f 100644
--- a/src/dune_engine/scheduler.ml
+++ b/src/dune_engine/scheduler.ml
@@ -680,23 +680,23 @@ type status =
   | (* Ready to start the next build. Waiting for a signal from the user, the
        test harness, or the polling loop. The payload is the collection of
        filesystem events. *)
-      Standing_by of
+    Standing_by of
       Memo.Invalidation.t
   | (* Waiting for file changes to start a new a build *)
-      Waiting_for_file_changes of
+    Waiting_for_file_changes of
       Memo.Invalidation.t Fiber.Ivar.t
   | (* Waiting for the propagation of inotify events to finish before starting a
        build. *)
-      Waiting_for_inotify_sync of
+    Waiting_for_inotify_sync of
       Memo.Invalidation.t * unit Fiber.Ivar.t
   | (* Running a build *)
-      Building
+    Building
   | (* Cancellation requested. Build jobs are immediately rejected in this
        state *)
-      Restarting_build of
+    Restarting_build of
       Memo.Invalidation.t
   | (* Shut down requested. No new new builds will start *)
-      Shutting_down
+    Shutting_down
 
 module Handler = struct
   module Event = struct
diff --git a/src/dune_rules/dir_status.ml b/src/dune_rules/dir_status.ml
index a8d83ce22..e5bd09477 100644
--- a/src/dune_rules/dir_status.ml
+++ b/src/dune_rules/dir_status.ml
@@ -12,15 +12,15 @@ module T = struct
     | Generated
     | Source_only of Source_tree.Dir.t
     | (* Directory not part of a multi-directory group *)
-        Standalone of
+      Standalone of
         Source_tree.Dir.t * Stanza.t list Dir_with_dune.t
     | (* Directory with [(include_subdirs x)] where [x] is not [no] *)
-        Group_root of
+      Group_root of
         Source_tree.Dir.t
         * (Loc.t * Include_subdirs.qualification)
         * Stanza.t list Dir_with_dune.t
     | (* Sub-directory of a [Group_root _] *)
-        Is_component_of_a_group_but_not_the_root of
+      Is_component_of_a_group_but_not_the_root of
         is_component_of_a_group_but_not_the_root
 end
 
diff --git a/src/dune_rules/lib.ml b/src/dune_rules/lib.ml
index 61b4a25c3..89f7ceb46 100644
--- a/src/dune_rules/lib.ml
+++ b/src/dune_rules/lib.ml
@@ -415,7 +415,7 @@ and resolve_result =
   | Hidden of Lib_info.external_ Hidden.t
   | Invalid of exn
   | (* Redirect (None, lib) looks up lib in the same database *)
-      Redirect of
+    Redirect of
       db option * (Loc.t * Lib_name.t)
 
 let lib_config (t : lib) = t.lib_config
diff --git a/lambda/lambda.mli b/lambda/lambda.mli
index c248801a3..02af3ebe7 100644
--- a/lambda/lambda.mli
+++ b/lambda/lambda.mli
@@ -379,8 +379,7 @@ and lambda_switch =
     sw_blocks : (int * lambda) list
   ; (* Tag block cases *)
     sw_failaction : lambda option
-  }
-(* Action to take if failure *)
+  } (* Action to take if failure *)
 
 and lambda_event =
   { lev_loc : scoped_location
diff --git a/lambda/translmod.ml b/lambda/translmod.ml
index 4edbb0773..444700fa8 100644
--- a/lambda/translmod.ml
+++ b/lambda/translmod.ml
@@ -1496,9 +1496,7 @@ let transl_store_implementation module_name (str, restr) =
 
 let toploop_ident = Ident.create_persistent "Toploop"
 let toploop_getvalue_pos = 0 (* position of getvalue in module Toploop *)
-
 let toploop_setvalue_pos = 1 (* position of setvalue in module Toploop *)
-
 let aliased_idents = ref Ident.empty
 
 let set_toplevel_unique_name id =
diff --git a/lambda/translobj.mli b/lambda/translobj.mli
index e642dadb1..7320d5091 100644
--- a/lambda/translobj.mli
+++ b/lambda/translobj.mli
@@ -22,7 +22,6 @@ val reset_labels : unit -> unit
 val transl_label_init : (unit -> lambda * 'a) -> lambda * 'a
 val transl_store_label_init : Ident.t -> int -> ('a -> lambda) -> 'a -> int * lambda
 val method_ids : Ident.Set.t ref (* reset when starting a new wrapper *)
-
 val oo_wrap : Env.t -> bool -> ('a -> lambda) -> 'a -> lambda
 val oo_add_class : Ident.t -> Env.t * bool
 val reset : unit -> unit
```

</details>

Diff for the `conventional` profile:

<details>

```diff
diff --git a/infer/src/erlang/ErlangAst.ml b/infer/src/erlang/ErlangAst.ml
index 8e7a308bd..0ac5b600f 100644
--- a/infer/src/erlang/ErlangAst.ml
+++ b/infer/src/erlang/ErlangAst.ml
@@ -117,7 +117,8 @@ and simple_expression =
   | Nil
   | Receive of { cases : case_clause list; timeout : timeout option }
   | RecordAccess of { record : expression; name : record_name; field : string }
-  | RecordIndex of { name : record_name; field : string } (* factor from above? *)
+  | RecordIndex of { name : record_name; field : string }
+  (* factor from above? *)
   | RecordUpdate of {
       record : expression option;
       name : record_name;
diff --git a/src/dune_engine/rules.mli b/src/dune_engine/rules.mli
index 82c9253d4..1301bba50 100644
--- a/src/dune_engine/rules.mli
+++ b/src/dune_engine/rules.mli
@@ -27,7 +27,7 @@ module Dir_rules : sig
 
            When passing [--force] to Dune, these are exactly the actions that
            will be re-executed. *)
-          Action of
+        Action of
           Rule.Anonymous_action.t Action_builder.t
 
     type t = { expansions : (Loc.t * item) Appendable_list.t } [@@unboxed]
diff --git a/src/dune_engine/scheduler.ml b/src/dune_engine/scheduler.ml
index 846af215e..1e238cfde 100644
--- a/src/dune_engine/scheduler.ml
+++ b/src/dune_engine/scheduler.ml
@@ -646,23 +646,23 @@ type status =
   | (* Ready to start the next build. Waiting for a signal from the user, the
        test harness, or the polling loop. The payload is the collection of
        filesystem events. *)
-      Standing_by of
+    Standing_by of
       Memo.Invalidation.t
   | (* Waiting for file changes to start a new a build *)
-      Waiting_for_file_changes of
+    Waiting_for_file_changes of
       Memo.Invalidation.t Fiber.Ivar.t
   | (* Waiting for the propagation of inotify events to finish before starting a
        build. *)
-      Waiting_for_inotify_sync of
+    Waiting_for_inotify_sync of
       Memo.Invalidation.t * unit Fiber.Ivar.t
   | (* Running a build *)
-      Building
+    Building
   | (* Cancellation requested. Build jobs are immediately rejected in this
        state *)
-      Restarting_build of
+    Restarting_build of
       Memo.Invalidation.t
   | (* Shut down requested. No new new builds will start *)
-      Shutting_down
+    Shutting_down
 
 module Handler = struct
   module Event = struct
diff --git a/src/dune_rules/dir_status.ml b/src/dune_rules/dir_status.ml
index 9e188e0a4..32f60bacf 100644
--- a/src/dune_rules/dir_status.ml
+++ b/src/dune_rules/dir_status.ml
@@ -12,15 +12,15 @@ module T = struct
     | Generated
     | Source_only of Source_tree.Dir.t
     | (* Directory not part of a multi-directory group *)
-        Standalone of
+      Standalone of
         Source_tree.Dir.t * Stanza.t list Dir_with_dune.t
     | (* Directory with [(include_subdirs x)] where [x] is not [no] *)
-        Group_root of
+      Group_root of
         Source_tree.Dir.t
         * (Loc.t * Include_subdirs.qualification)
         * Stanza.t list Dir_with_dune.t
     | (* Sub-directory of a [Group_root _] *)
-        Is_component_of_a_group_but_not_the_root of
+      Is_component_of_a_group_but_not_the_root of
         is_component_of_a_group_but_not_the_root
 end
 
diff --git a/src/dune_rules/lib.ml b/src/dune_rules/lib.ml
index dcf6ec5e0..09d4d8bd1 100644
--- a/src/dune_rules/lib.ml
+++ b/src/dune_rules/lib.ml
@@ -368,7 +368,7 @@ and resolve_result =
   | Hidden of Lib_info.external_ Hidden.t
   | Invalid of exn
   | (* Redirect (None, lib) looks up lib in the same database *)
-      Redirect of
+    Redirect of
       db option * (Loc.t * Lib_name.t)
 
 let lib_config (t : lib) = t.lib_config
diff --git a/lambda/lambda.mli b/lambda/lambda.mli
index 3b9670832..68ee67e85 100644
--- a/lambda/lambda.mli
+++ b/lambda/lambda.mli
@@ -345,8 +345,7 @@ and lambda_switch = {
   sw_blocks : (int * lambda) list;
   (* Tag block cases *)
   sw_failaction : lambda option;
-}
-(* Action to take if failure *)
+} (* Action to take if failure *)
 
 and lambda_event = {
   lev_loc : scoped_location;
```

</details>

### CODE REVIEW

File: test/passing/tests/wrap_comments.ml.ref [hunk 1]
```diff
@@ -33,7 +33,8 @@ let _ =
 [@@@ocamlformat "wrap-comments=false"]
 
 type t =
-  | Aaaaaaaaaa (* Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. *)
+  | Aaaaaaaaaa
+  (* Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. *)
```
[the remark this answers is not in the document]
Comment (jberdine) [reply test/passing/tests/wrap_comments.ml.ref:37]: It is not clear to me that this is a regression. The comment exceeds the margin, doesn't it. In that case, it is perfectly legit to break before it.

**Review by jberdine — COMMENTED** [review]
This is draft but I rebased onto main and tested, and the results look good. Is there anything blocking this?

File: test/passing/tests/wrap_comments.ml.ref (hunk 1 above)
[the remark this answers is not in the document]
Comment (gpetiot) [reply test/passing/tests/wrap_comments.ml.ref:37]: I think it's because it's now considered to be attached before the next constructor, instead of after the previous one. I've been working on another branch to add a location to the `Parsetree.case` type so that the bar symbol would be part of the location and we wouldn't have dedicated shenanigans in Cmts.ml to handle that, but there were still some regressions.

**Comment by gpetiot** [comment]
@Julow @jberdine I've revived this PR, let me know what you think.

We can extract the rewriting of pattern lists (making them consistent with exp lists) in a separate PR of course, this change (rather the resulting comment relocation) is required to not have regressions with the new comment attachment.

**Review by mjambon — APPROVED** [review]
I can't really comment on the implementation but the updated test samples look good to me. I'm very excited about this.

File: lib/Fmt_ast.ml [hunk 2]
```diff
@@ -1566,6 +1581,51 @@ and fmt_infix_op_args ?ext c ~parens xexp op_args =
...
+         (fun ~first ~last (_, cmts_before, cmts_after, (op, xargs)) ->
+           let very_first = first_grp && first in
+           let very_last = last_grp && last in
+           cmts_before
+           $ hvbox 0
+               ( op
+               $ ( match xargs with
+                 | (_, e) :: _ when very_last && is_not_indented e ->
+                     fmt "@ "
+                 | _ -> fmt_if (not very_first) " " )
```
Comment (Julow) [inline lib/Fmt_ast.ml:1617]: Do you have an example where `Ppat_open` needs a break after it ? All the tests run fine with
```suggestion
               $ fmt_if (not very_first) " "
```

File: lib/Source.ml [hunk 3]
```diff
@@ -116,6 +116,12 @@ let is_long_pexp_open source {pexp_desc; _} =
       contains_token_between source ~from ~upto Parser.IN
   | _ -> false
 
+let is_long_ppat_open source {ppat_desc; _} =
+  match ppat_desc with
+  | Ppat_open ({loc= from; _}, {ppat_loc= upto; _}) ->
+      contains_token_between source ~from ~upto Parser.IN
```
Comment (Julow) [inline lib/Source.ml:122]: I don't expect this token in a pattern. What's a "long" ppat open ?

Comment (gpetiot) [reply lib/Source.ml:122]: Ah yes the `let open` syntax is not possible indeed, I didn't even check, I will remove this

File: lib/Fmt_ast.ml (hunk 2 above)
Comment (gpetiot) [reply lib/Fmt_ast.ml]: not necessary indeed

File: test/passing/tests/wrap_comments.ml.ref (hunk 1 above)
[the remark this answers is not in the document]
Comment (gpetiot) [reply test/passing/tests/wrap_comments.ml.ref]: regression fixed

File: test/passing/tests/js_source.ml.ref [hunk 4]
```diff
@@ -532,7 +531,6 @@ let n2 = extension_name (Bar 1)
 let t = extension_id (Bar 2) = extension_id (Bar 3) (* true *)
 
 let f = extension_id (Bar 2) = extension_id Foo (* false *)
-
```
[the remark this answers is not in the document]
Comment (gpetiot) [reply test/passing/tests/js_source.ml.ref:535]: This is surprising indeed, no idea what is causing this

**Comment by gpetiot** [comment]
I've finished splitting this PR into smaller bits, I tried to extract the last change (the Cmts algorithm) to make something cleaner, maybe add some unit tests but depending on `Source.t` makes it hard to achieve. It would be nice to find a new representation that is easier to test in the future.

Here is the updated diff for the conventional profile:

<details>

```diff
diff --git a/infer/src/topl/ToplAst.ml b/infer/src/topl/ToplAst.ml
index 0a749ec4f..6c1be44ff 100644
--- a/infer/src/topl/ToplAst.ml
+++ b/infer/src/topl/ToplAst.ml
@@ -22,7 +22,6 @@ type binop = (* all return booleans *)
 
 type predicate = Binop of binop * value * value | Value of (* bool *) value
 type condition = predicate list (* conjunction *)
-
 type assignment = register_name * variable_name
 
 type procedure_name_pattern = string
diff --git a/asmcomp/arm64/proc.ml b/asmcomp/arm64/proc.ml
index bf189358f..8b1efea35 100644
--- a/asmcomp/arm64/proc.ml
+++ b/asmcomp/arm64/proc.ml
@@ -218,7 +218,6 @@ let not_supported _ofs = fatal_error "Proc.loc_results: cannot call"
    Return values in r0...r15 or d0...d15. *)
 
 let max_arguments_for_tailcalls = 16 (* in regs *) + 64 (* in domain state *)
-
 let last_int_register = if macosx then 7 else 15
 
 let loc_arguments arg =
diff --git a/boot/menhir/menhirLib.ml b/boot/menhir/menhirLib.ml
index 36de0950b..41c0fd077 100644
--- a/boot/menhir/menhirLib.ml
+++ b/boot/menhir/menhirLib.ml
@@ -2194,7 +2194,6 @@ module InfiniteArray = struct
   }
 
   let default_size = 16384 (* must be non-zero *)
-
   let make x = { default = x; table = Array.make default_size x; extent = 0 }
 
   let rec new_length length i =
diff --git a/debugger/symbols.ml b/debugger/symbols.ml
index 89d88db8a..f6b1d8382 100644
--- a/debugger/symbols.ml
+++ b/debugger/symbols.ml
@@ -18,7 +18,6 @@
 
 open Instruct
 open Debugger_config (* Toplevel *)
-
 open Program_loading
 open Debugcom
 open Events
diff --git a/lambda/translmod.ml b/lambda/translmod.ml
index c623940a5..31f7805e3 100644
--- a/lambda/translmod.ml
+++ b/lambda/translmod.ml
@@ -1571,9 +1571,7 @@ let transl_store_implementation module_name (str, restr) =
 
 let toploop_ident = Ident.create_persistent "Toploop"
 let toploop_getvalue_pos = 0 (* position of getvalue in module Toploop *)
-
 let toploop_setvalue_pos = 1 (* position of setvalue in module Toploop *)
-
 let aliased_idents = ref Ident.empty
 
 let set_toplevel_unique_name id =
diff --git a/lambda/translobj.mli b/lambda/translobj.mli
index dc28d3b08..3ece464a4 100644
--- a/lambda/translobj.mli
+++ b/lambda/translobj.mli
@@ -25,7 +25,6 @@ val transl_store_label_init :
   Ident.t -> int -> ('a -> lambda) -> 'a -> int * lambda
 
 val method_ids : Ident.Set.t ref (* reset when starting a new wrapper *)
-
 val oo_wrap : Env.t -> bool -> ('a -> lambda) -> 'a -> lambda
 val oo_add_class : Ident.t -> Env.t * bool
 val reset : unit -> unit
diff --git a/ocamltest/ocaml_toplevels.ml b/ocamltest/ocaml_toplevels.ml
index 346070319..1930c74ca 100644
--- a/ocamltest/ocaml_toplevels.ml
+++ b/ocamltest/ocaml_toplevels.ml
@@ -51,8 +51,7 @@ let ocaml =
 let ocamlnat =
   new toplevel
     ~name:Ocaml_files.ocamlnat
-    ~flags:"-S" (* Keep intermediate assembly files *)
-    ~directory:"ocamlnat"
+    ~flags:"-S" (* Keep intermediate assembly files *) ~directory:"ocamlnat"
     ~exit_status_variable:Ocaml_variables.ocamlnat_exit_status
     ~reference_variable:Ocaml_variables.compiler_reference2
     ~output_variable:Ocaml_variables.compiler_output2
diff --git a/parsing/pprintast.ml b/parsing/pprintast.ml
index 4609921f4..d09c92a82 100644
--- a/parsing/pprintast.ml
+++ b/parsing/pprintast.ml
@@ -1025,8 +1025,9 @@ and class_expr ctxt f x =
     | Pcl_let (rf, l, ce) ->
         pp f "%a@ in@ %a" (bindings ctxt) (rf, l) (class_expr ctxt) ce
     | Pcl_apply (ce, l) ->
-        pp f "((%a)@ %a)" (* Cf: #7200 *)
-          (class_expr ctxt) ce
+        pp f "((%a)@ %a)"
+          (* Cf: #7200 *) (class_expr ctxt)
+          ce
           (list (label_x_expression_param ctxt))
           l
     | Pcl_constr (li, l) ->
diff --git a/stdlib/obj.mli b/stdlib/obj.mli
index 861c7d4c5..7e3d8c9e5 100644
--- a/stdlib/obj.mli
+++ b/stdlib/obj.mli
@@ -90,7 +90,6 @@ val forward_tag : int
 val no_scan_tag : int
 val abstract_tag : int
 val string_tag : int (* both [string] and [bytes] *)
-
 val double_tag : int
 val double_array_tag : int
 val custom_tag : int
diff --git a/testsuite/tests/asmcomp/is_static.ml b/testsuite/tests/asmcomp/is_static.ml
index 5f61c2857..886c5f082 100644
--- a/testsuite/tests/asmcomp/is_static.ml
+++ b/testsuite/tests/asmcomp/is_static.ml
@@ -25,7 +25,6 @@ let () = (f [@inlined never]) ()
 
 (* Closed functions should be static *)
 let closed_function x = x + 1 (* + is a primitive, it cannot be in the closure*)
-
 let () = assert (is_in_static_data closed_function)
 
 (* And functions using closed functions *)
diff --git a/testsuite/tests/lib-dynlink-private/test.ml b/testsuite/tests/lib-dynlink-private/test.ml
index ca5c0314c..0f057615f 100644
--- a/testsuite/tests/lib-dynlink-private/test.ml
+++ b/testsuite/tests/lib-dynlink-private/test.ml
@@ -168,7 +168,6 @@
 *)
 
 let () = Sheep.baa Sheep.s (* Use Sheep module *)
-
 let _ = fun (x : Pig.t) -> x (* Reference Pig module *)
 
 (* Test that a privately loaded module cannot have the same name as a
diff --git a/testsuite/tests/misc-unsafe/almabench.ml b/testsuite/tests/misc-unsafe/almabench.ml
index 145bece43..6ae6893ca 100644
--- a/testsuite/tests/misc-unsafe/almabench.ml
+++ b/testsuite/tests/misc-unsafe/almabench.ml
@@ -45,7 +45,6 @@ and gaussk = 0.01720209895
 
 (* number of days to include in test *)
 let test_loops = 5 (* was: 20 *)
-
 and test_length = 36525
 
 (* sin and cos of j2000 mean obliquity (iau 1976) *)
diff --git a/testsuite/tests/no-alias-deps/aliases.ml b/testsuite/tests/no-alias-deps/aliases.ml
index d48459fa9..3add9f0b4 100644
--- a/testsuite/tests/no-alias-deps/aliases.ml
+++ b/testsuite/tests/no-alias-deps/aliases.ml
@@ -12,11 +12,8 @@
 *)
 
 module A' = A (* missing a.cmi *)
-
 module B' = B (* broken b.cmi *)
-
 module C' = C (* valid c.cmi *)
-
 module D' = D (* valid d.cmi *)
 
 let () = print_int D'.something
diff --git a/testsuite/tests/regression/pr9326/gc_set.ml b/testsuite/tests/regression/pr9326/gc_set.ml
index 1c52b13a7..adb0d4603 100644
--- a/testsuite/tests/regression/pr9326/gc_set.ml
+++ b/testsuite/tests/regression/pr9326/gc_set.ml
@@ -4,10 +4,8 @@
 open Gc
 
 let min_heap_sz = 524288 (* 512k *)
-
 let space_overhead = 70
 let stack_limit = 4194304 (* 4M *)
-
 let custom_major_ratio = 40
 let custom_minor_ratio = 99
 let custom_minor_max_size = 4096
diff --git a/testsuite/tests/typing-gadts/pr7214.ml b/testsuite/tests/typing-gadts/pr7214.ml
index 4c2243739..ed7523f81 100644
--- a/testsuite/tests/typing-gadts/pr7214.ml
+++ b/testsuite/tests/typing-gadts/pr7214.ml
@@ -7,7 +7,6 @@ type _ t = I : int t
 let f (type a) (x : a t) =
   let module M = struct
     let (I : a t) = x (* fail because of toplevel let *)
-
     let x = (I : a t)
   end in
   ()
@@ -33,7 +32,6 @@ let bad (type a) =
       val e : (int, a) eq
     end = struct
       let (Refl : (int, a) eq) = M.e (* must fail for soundness *)
-
       let e : (int, a) eq = Refl
     end
   end in
diff --git a/testsuite/tests/typing-misc/injectivity.ml b/testsuite/tests/typing-misc/injectivity.ml
index e2669c3e8..d048bd9a5 100644
--- a/testsuite/tests/typing-misc/injectivity.ml
+++ b/testsuite/tests/typing-misc/injectivity.ml
@@ -46,7 +46,6 @@ module M : sig type +!'a t end
 |}]
 
 type _ t = M : 'a -> 'a M.t t (* OK *)
-
 type 'a u = 'b constraint 'a = 'b M.t
 
 [%%expect
diff --git a/testsuite/tests/typing-signatures/els.ml b/testsuite/tests/typing-signatures/els.ml
index a70101f2f..e7ded5f02 100644
--- a/testsuite/tests/typing-signatures/els.ml
+++ b/testsuite/tests/typing-signatures/els.ml
@@ -7,9 +7,7 @@
 
 module type VALUE = sig
   type value (* a Lua value *)
-
   type state (* the state of a Lua interpreter *)
-
   type usert (* a user-defined value *)
 end
 
diff --git a/testsuite/tests/warnings/w06.ml b/testsuite/tests/warnings/w06.ml
index a7cd1b256..e4c967dc7 100644
--- a/testsuite/tests/warnings/w06.ml
+++ b/testsuite/tests/warnings/w06.ml
@@ -9,7 +9,6 @@
 *)
 
 let foo ~bar = ignore bar (* one label *)
-
 let bar ~foo ~baz = ignore (foo, baz) (* two labels *)
 
 let () = foo 2
diff --git a/testsuite/tests/warnings/w33.ml b/testsuite/tests/warnings/w33.ml
index 8c1a60206..f714f748b 100644
--- a/testsuite/tests/warnings/w33.ml
+++ b/testsuite/tests/warnings/w33.ml
@@ -22,9 +22,7 @@ module R = struct
 end
 
 let f M.(x) = x (* useless open *)
-
 let g N.(A | B) = () (* used open *)
-
 let h R.{ x } = R.{ x }
 
 open N (* used open *)
@@ -32,5 +30,4 @@ open N (* used open *)
 let i (A | B) = B
 
 open! M (* useless open! *)
-
 open M (* useless open *)
diff --git a/testsuite/tests/warnings/w45.ml b/testsuite/tests/warnings/w45.ml
index 3c99fbf7c..754bd5146 100644
--- a/testsuite/tests/warnings/w45.ml
+++ b/testsuite/tests/warnings/w45.ml
@@ -20,7 +20,6 @@ end
 
 module T3 = struct
   open T1 (* unused open *)
-
   open T2 (* shadow X, which is later used; but not A, see #6762 *)
 
   let _ = (A, X) (* X belongs to several types *)
diff --git a/testsuite/tests/warnings/w47_inline.ml b/testsuite/tests/warnings/w47_inline.ml
index 6cd07163a..f1a7c33c1 100644
--- a/testsuite/tests/warnings/w47_inline.ml
+++ b/testsuite/tests/warnings/w47_inline.ml
@@ -9,27 +9,16 @@
 *)
 
 let a = fun [@inline] x -> x (* accepted *)
-
 let b = fun [@inline never] x -> x (* accepted *)
-
 let c = fun [@inline always] x -> x (* accepted *)
-
 let d = fun [@inline malformed attribute] x -> x (* rejected *)
-
 let e = fun [@inline malformed_attribute] x -> x (* rejected *)
-
 let f = fun [@inline: malformed_attribute] x -> x (* rejected *)
-
 let g = fun [@inline? malformed_attribute] x -> x (* rejected *)
-
 let h x = (a [@inlined]) x (* accepted *)
-
 let i x = (a [@inlined never]) x (* accepted *)
-
 let j x = (a [@inlined always]) x (* accepted *)
-
 let k x = (a [@inlined malformed]) x (* rejected *)
-
 let l x = x [@@inline] (* accepted *)
 
 let test x =
diff --git a/testsuite/tests/warnings/w53.ml b/testsuite/tests/warnings/w53.ml
index 9e4d4abd5..515645029 100644
--- a/testsuite/tests/warnings/w53.ml
+++ b/testsuite/tests/warnings/w53.ml
@@ -17,9 +17,7 @@ let i x = (x [@inlined]) (* rejected *)
 let j x = (x [@ocaml.inlined]) (* rejected *)
 
 let k x = (h [@inlined]) x (* accepted *)
-
 let k' x = (h [@ocaml.inlined]) x (* accepted *)
-
 let l x = (h x [@inlined]) (* rejected *)
 
 let m x = (x [@tailcall]) (* rejected *)
@@ -27,9 +25,7 @@ let m x = (x [@tailcall]) (* rejected *)
 let n x = (x [@ocaml.tailcall]) (* rejected *)
 
 let o x = (h [@tailcall]) x (* accepted *)
-
 let p x = (h [@ocaml.tailcall]) x (* accepted *)
-
 let q x = (h x [@tailcall]) (* rejected *)
 
 module type E = sig end
diff --git a/testsuite/tests/warnings/w54.ml b/testsuite/tests/warnings/w54.ml
index f0a22c858..bc0827c5f 100644
--- a/testsuite/tests/warnings/w54.ml
+++ b/testsuite/tests/warnings/w54.ml
@@ -12,5 +12,4 @@ let f = fun [@inline] [@inline never] x -> x
 let g = fun [@inline] [@something_else] [@ocaml.inline] x -> x
 let h x = (g [@inlined] [@ocaml.inlined never]) x
 let v = (fun [@inline] [@inlined] x -> x) 1 (* accepted *)
-
 let i = fun [@inline] x -> x [@@inline]
diff --git a/tools/dumpobj.ml b/tools/dumpobj.ml
index aa2937299..950ba7fd6 100644
--- a/tools/dumpobj.ml
+++ b/tools/dumpobj.ml
@@ -50,7 +50,6 @@ let inputs ic =
 type global_table_entry = Empty | Global of Ident.t | Constant of Obj.t
 
 let start = ref 0 (* Position of beg. of code *)
-
 let reloc = ref ([] : (reloc_info * int) list) (* Relocation table *)
 
 let globals = ref ([||] : global_table_entry array) (* Global map *)
diff --git a/tools/ocamlmklib.ml b/tools/ocamlmklib.ml
index 99fff7a25..c02119f62 100644
--- a/tools/ocamlmklib.ml
+++ b/tools/ocamlmklib.ml
@@ -33,42 +33,27 @@ let compiler_path name =
   if Sys.os_type = "Win32" then name else Filename.concat Config.bindir name
 
 let bytecode_objs = ref [] (* .cmo,.cma,.ml,.mli files to pass to ocamlc *)
-
 and native_objs = ref [] (* .cmx,.ml,.mli files to pass to ocamlopt *)
-
 and c_objs = ref []
 (* .o, .a, .obj, .lib, .dll, .dylib, .so files to
    pass to mksharedlib and ar *)
 
 and caml_libs = ref [] (* -cclib to pass to ocamlc, ocamlopt *)
-
 and caml_opts = ref [] (* -ccopt to pass to ocamlc, ocamlopt *)
-
 and dynlink = ref Config.supports_shared_libraries
 and failsafe = ref false (* whether to fall back on static build only *)
-
 and c_libs = ref [] (* libs to pass to mksharedlib and ocamlc -cclib *)
-
 and c_Lopts = ref [] (* options to pass to mksharedlib and ocamlc -cclib *)
-
 and c_opts = ref [] (* options to pass to mksharedlib and ocamlc -ccopt *)
-
 and ld_opts = ref [] (* options to pass only to the linker *)
-
 and ocamlc = ref (compiler_path "ocamlc")
 and ocamlc_opts = ref [] (* options to pass only to ocamlc *)
-
 and ocamlopt = ref (compiler_path "ocamlopt")
 and ocamlopt_opts = ref [] (* options to pass only to ocamlc *)
-
 and output = ref "a" (* Output name for OCaml part of library *)
-
 and output_c = ref "" (* Output name for C part of library *)
-
 and rpath = ref [] (* rpath options *)
-
 and debug = ref false (* -g option *)
-
 and verbose = ref false
 
 let starts_with s pref =
diff --git a/typing/ctype.ml b/typing/ctype.ml
index ea1a5b88f..6ac6a4eab 100644
--- a/typing/ctype.ml
+++ b/typing/ctype.ml
@@ -1711,7 +1711,6 @@ let rec occur_rec env allow_recursive visited ty0 ty =
         iter_type_expr (occur_rec env allow_recursive visited ty0) ty
 
 let type_changed = ref false (* trace possible changes to the studied type *)
-
 let merge r b = if b then r := true
 
 let occur env ty0 ty =
@@ -4354,7 +4353,6 @@ let match_class_declarations env patt_params patt_type subj_params subj_type =
    [level] number of expansions/enlargement allowed on this branch *)
 
 let warn = ref false (* whether double coercion might do better *)
-
 let pred_expand n = if n mod 2 = 0 && n > 0 then pred n else n
 let pred_enlarge n = if n mod 2 = 1 then pred n else n
 
diff --git a/typing/types.mli b/typing/types.mli
index f24719e88..1ad9bf9f5 100644
--- a/typing/types.mli
+++ b/typing/types.mli
@@ -402,13 +402,9 @@ module Variance : sig
   (* both negative and positive occurrences *)
 
   val null : t (* no occurrence *)
-
   val full : t (* strictly invariant (all flags) *)
-
   val covariant : t (* strictly covariant (May_pos, Pos and Inj) *)
-
   val unknown : t (* allow everything, guarantee nothing *)
-
   val union : t -> t -> t
   val inter : t -> t -> t
   val subset : t -> t -> bool
@@ -416,9 +412,7 @@ module Variance : sig
   val set : f -> bool -> t -> t
   val mem : f -> t -> bool
   val conjugate : t -> t (* exchange positive and negative *)
-
   val get_upper : t -> bool * bool (* may_pos, may_neg   *)
-
   val get_lower : t -> bool * bool * bool * bool (* pos, neg, inv, inj *)
 
   val unknown_signature : injective:bool -> arity:int -> t list
diff --git a/utils/clflags.ml b/utils/clflags.ml
index eaf749b52..0ee594a6c 100644
--- a/utils/clflags.ml
+++ b/utils/clflags.ml
@@ -51,200 +51,122 @@ and dllibs = ref ([] : string list)
 (* .so and -dllib -lxxx *)
 
 let compile_only = ref false (* -c *)
-
 and output_name = ref (None : string option) (* -o *)
 
 and include_dirs = ref ([] : string list) (* -I *)
 
 and no_std_include = ref false (* -nostdlib *)
-
 and print_types = ref false (* -i *)
-
 and make_archive = ref false (* -a *)
-
 and debug = ref false (* -g *)
-
 and debug_full = ref false (* For full DWARF support *)
-
 and unsafe = ref false (* -unsafe *)
-
 and use_linscan = ref false (* -linscan *)
-
 and link_everything = ref false (* -linkall *)
-
 and custom_runtime = ref false (* -custom *)
-
 and no_check_prims = ref false (* -no-check-prims *)
-
 and bytecode_compatible_32 = ref false (* -compat-32 *)
-
 and output_c_object = ref false (* -output-obj *)
-
 and output_complete_object = ref false (* -output-complete-obj *)
-
 and output_complete_executable = ref false (* -output-complete-exe *)
-
 and all_ccopts = ref ([] : string list) (* -ccopt *)
 
 and classic = ref false (* -nolabels *)
-
 and nopervasives = ref false (* -nopervasives *)
-
 and match_context_rows = ref 32 (* -match-context-rows *)
-
 and preprocessor = ref (None : string option) (* -pp *)
 
 and all_ppx = ref ([] : string list)
 (* -ppx *)
 
 let absname = ref false (* -absname *)
-
 let annotations = ref false (* -annot *)
 
 let binary_annotations = ref false (* -bin-annot *)
-
 and use_threads = ref false (* -thread *)
-
 and noassert = ref false (* -noassert *)
-
 and verbose = ref false (* -verbose *)
-
 and noversion = ref false (* -no-version *)
-
 and noprompt = ref false (* -noprompt *)
-
 and nopromptcont = ref false (* -nopromptcont *)
-
 and init_file = ref (None : string option) (* -init *)
 
 and noinit = ref false (* -noinit *)
-
 and open_modules = ref [] (* -open *)
-
 and use_prims = ref "" (* -use-prims ... *)
-
 and use_runtime = ref "" (* -use-runtime ... *)
-
 and plugin = ref false (* -plugin ... *)
-
 and principal = ref false (* -principal *)
-
 and real_paths = ref true (* -short-paths *)
-
 and recursive_types = ref false (* -rectypes *)
-
 and strict_sequence = ref false (* -strict-sequence *)
-
 and strict_formats = ref false (* -strict-formats *)
-
 and applicative_functors = ref true (* -no-app-funct *)
-
 and make_runtime = ref false (* -make-runtime *)
-
 and c_compiler = ref (None : string option) (* -cc *)
 
 and no_auto_link = ref false (* -noautolink *)
-
 and dllpaths = ref ([] : string list) (* -dllpath *)
 
 and make_package = ref false (* -pack *)
-
 and for_package = ref (None : string option) (* -for-pack *)
 
 and error_size = ref 500 (* -error-size *)
-
 and float_const_prop = ref true (* -no-float-const-prop *)
-
 and transparent_modules = ref false
 (* -trans-mod *)
 
 let unique_ids = ref true (* -d(no-)unique-ds *)
-
 let locations = ref true (* -d(no-)locations *)
-
 let dump_source = ref false (* -dsource *)
 
 let dump_parsetree = ref false (* -dparsetree *)
-
 and dump_typedtree = ref false (* -dtypedtree *)
-
 and dump_shape = ref false (* -dshape *)
-
 and dump_rawlambda = ref false (* -drawlambda *)
-
 and dump_lambda = ref false (* -dlambda *)
-
 and dump_rawclambda = ref false (* -drawclambda *)
-
 and dump_clambda = ref false (* -dclambda *)
-
 and dump_rawflambda = ref false (* -drawflambda *)
-
 and dump_flambda = ref false (* -dflambda *)
-
 and dump_flambda_let = ref (None : int option) (* -dflambda-let=... *)
 
 and dump_flambda_verbose = ref false (* -dflambda-verbose *)
-
 and dump_instr = ref false (* -dinstr *)
-
 and keep_camlprimc_file = ref false
 (* -dcamlprimc *)
 
 let keep_asm_file = ref false (* -S *)
 
 let optimize_for_speed = ref true (* -compact *)
-
 and opaque = ref false (* -opaque *)
-
 and dump_cmm = ref false
 (* -dcmm *)
 
 let dump_selection = ref false (* -dsel *)
-
 let dump_cse = ref false (* -dcse *)
-
 let dump_live = ref false (* -dlive *)
-
 let dump_spill = ref false (* -dspill *)
-
 let dump_split = ref false (* -dsplit *)
-
 let dump_interf = ref false (* -dinterf *)
-
 let dump_prefer = ref false (* -dprefer *)
-
 let dump_regalloc = ref false (* -dalloc *)
-
 let dump_reload = ref false (* -dreload *)
-
 let dump_scheduling = ref false (* -dscheduling *)
-
 let dump_linear = ref false (* -dlinear *)
-
 let dump_interval = ref false (* -dinterval *)
-
 let keep_startup_file = ref false (* -dstartup *)
-
 let dump_combine = ref false (* -dcombine *)
-
 let profile_columns : Profile.column list ref = ref [] (* -dprofile/-dtimings *)
-
 let native_code = ref false (* set to true under ocamlopt *)
-
 let force_tmc = ref false (* -force-tmc *)
-
 let force_slash = ref false (* for ocamldep *)
-
 let clambda_checks = ref false (* -clambda-checks *)
-
 let cmm_invariants = ref Config.with_cmm_invariants (* -dcmm-invariants *)
-
 let flambda_invariant_checks = ref Config.with_flambda_invariants
 (* -flambda-(no-)invariants *)
 
 let dont_write_files = ref false (* set to true under ocamldoc *)
-
 let insn_sched_default = true
 let insn_sched = ref insn_sched_default (* -[no-]insn-sched *)
 
@@ -256,7 +178,6 @@ let std_include_dir () =
   if !no_std_include then [] else [ Config.standard_library ]
 
 let shared = ref false (* -shared *)
-
 let dlcode = ref true (* not -nodynlink *)
 
 let pic_code =
@@ -275,7 +196,6 @@ let with_runtime = ref true
 (* -with-runtime *)
 
 let keep_docs = ref false (* -keep-docs *)
-
 let keep_locs = ref true (* -keep-locs *)
 
 let unsafe_string =
@@ -283,17 +203,11 @@ let unsafe_string =
 (* -safe-string / -unsafe-string *)
 
 let classic_inlining = ref false (* -Oclassic *)
-
 let inlining_report = ref false (* -inlining-report *)
-
 let afl_instrument = ref Config.afl_instrument (* -afl-instrument *)
-
 let afl_inst_ratio = ref 100 (* -afl-inst-ratio *)
-
 let function_sections = ref false (* -function-sections *)
-
 let simplify_rounds = ref None (* -rounds *)
-
 let default_simplify_rounds = ref 1 (* -rounds *)
 
 let rounds () =
@@ -336,10 +250,8 @@ let inline_lifting_benefit =
 let inline_max_unroll = ref (Int_arg_helper.default default_inline_max_unroll)
 let inline_max_depth = ref (Int_arg_helper.default default_inline_max_depth)
 let unbox_specialised_args = ref true (* -no-unbox-specialised-args *)
-
 let unbox_free_vars_of_closures = ref true
 let unbox_closures = ref false (* -unbox-closures *)
-
 let default_unbox_closures_factor = 10
 let unbox_closures_factor = ref default_unbox_closures_factor
 (* -unbox-closures-factor *)
@@ -478,7 +390,6 @@ let set_dumped_pass s enabled =
     dumped_passes_list := dumped_passes
 
 let dump_into_file = ref false (* -dump-into-file *)
-
 let dump_dir : string option ref = ref None (* -dump-dir *)
 
 type 'a env_reader = {
```

</details>

And the diff for the janestreet profile:

<details>

```diff
diff --git a/stdlib/obj.mli b/stdlib/obj.mli
index 7cc823ef0..00c58aa66 100644
--- a/stdlib/obj.mli
+++ b/stdlib/obj.mli
@@ -88,7 +88,6 @@ val forward_tag : int
 val no_scan_tag : int
 val abstract_tag : int
 val string_tag : int (* both [string] and [bytes] *)
-
 val double_tag : int
 val double_array_tag : int
 val custom_tag : int
diff --git a/testsuite/tests/asmcomp/is_static.ml b/testsuite/tests/asmcomp/is_static.ml
index 315070db7..3eee2bbcc 100644
--- a/testsuite/tests/asmcomp/is_static.ml
+++ b/testsuite/tests/asmcomp/is_static.ml
@@ -26,7 +26,6 @@ let () = (f [@inlined never]) ()
 
 (* Closed functions should be static *)
 let closed_function x = x + 1 (* + is a primitive, it cannot be in the closure*)
-
 let () = assert (is_in_static_data closed_function)
 
 (* And functions using closed functions *)
diff --git a/testsuite/tests/lib-dynlink-private/test.ml b/testsuite/tests/lib-dynlink-private/test.ml
index 7cd1c2e09..aef225431 100644
--- a/testsuite/tests/lib-dynlink-private/test.ml
+++ b/testsuite/tests/lib-dynlink-private/test.ml
@@ -168,7 +168,6 @@ all_modules = "sheep.cmx test.cmx"
 *)
 
 let () = Sheep.baa Sheep.s (* Use Sheep module *)
-
 let _ = fun (x : Pig.t) -> x (* Reference Pig module *)
 
 (* Test that a privately loaded module cannot have the same name as a
diff --git a/testsuite/tests/misc-unsafe/almabench.ml b/testsuite/tests/misc-unsafe/almabench.ml
index 50bb92ce2..3ba24f93e 100644
--- a/testsuite/tests/misc-unsafe/almabench.ml
+++ b/testsuite/tests/misc-unsafe/almabench.ml
@@ -45,7 +45,6 @@ and gaussk = 0.01720209895
 
 (* number of days to include in test *)
 let test_loops = 5 (* was: 20 *)
-
 and test_length = 36525
 
 (* sin and cos of j2000 mean obliquity (iau 1976) *)
diff --git a/testsuite/tests/no-alias-deps/aliases.ml b/testsuite/tests/no-alias-deps/aliases.ml
index ab01568b8..34702cb43 100644
--- a/testsuite/tests/no-alias-deps/aliases.ml
+++ b/testsuite/tests/no-alias-deps/aliases.ml
@@ -12,11 +12,8 @@ program = "aliases.cmo"
 *)
 
 module A' = A (* missing a.cmi *)
-
 module B' = B (* broken b.cmi *)
-
 module C' = C (* valid c.cmi *)
-
 module D' = D (* valid d.cmi *)
 
 let () = print_int D'.something
diff --git a/testsuite/tests/regression/pr9326/gc_set.ml b/testsuite/tests/regression/pr9326/gc_set.ml
index 80fc2a696..656d9e3c6 100644
--- a/testsuite/tests/regression/pr9326/gc_set.ml
+++ b/testsuite/tests/regression/pr9326/gc_set.ml
@@ -4,10 +4,8 @@
 open Gc
 
 let min_heap_sz = 524288 (* 512k *)
-
 let space_overhead = 70
 let stack_limit = 4194304 (* 4M *)
-
 let custom_major_ratio = 40
 let custom_minor_ratio = 99
 let custom_minor_max_size = 4096
diff --git a/testsuite/tests/typing-gadts/pr7214.ml b/testsuite/tests/typing-gadts/pr7214.ml
index ab059fe72..a7474e548 100644
--- a/testsuite/tests/typing-gadts/pr7214.ml
+++ b/testsuite/tests/typing-gadts/pr7214.ml
@@ -7,7 +7,6 @@ type _ t = I : int t
 let f (type a) (x : a t) =
   let module M = struct
     let (I : a t) = x (* fail because of toplevel let *)
-
     let x = (I : a t)
   end
   in
@@ -35,7 +34,6 @@ let bad (type a) =
       val e : (int, a) eq
     end = struct
       let (Refl : (int, a) eq) = M.e (* must fail for soundness *)
-
       let e : (int, a) eq = Refl
     end
   end
diff --git a/testsuite/tests/typing-misc/injectivity.ml b/testsuite/tests/typing-misc/injectivity.ml
index 33490a9d0..74d4aff76 100644
--- a/testsuite/tests/typing-misc/injectivity.ml
+++ b/testsuite/tests/typing-misc/injectivity.ml
@@ -46,7 +46,6 @@ module M : sig type +!'a t end
 |}]
 
 type _ t = M : 'a -> 'a M.t t (* OK *)
-
 type 'a u = 'b constraint 'a = 'b M.t
 
 [%%expect {|
diff --git a/testsuite/tests/typing-signatures/els.ml b/testsuite/tests/typing-signatures/els.ml
index a70101f2f..e7ded5f02 100644
--- a/testsuite/tests/typing-signatures/els.ml
+++ b/testsuite/tests/typing-signatures/els.ml
@@ -7,9 +7,7 @@
 
 module type VALUE = sig
   type value (* a Lua value *)
-
   type state (* the state of a Lua interpreter *)
-
   type usert (* a user-defined value *)
 end
 
diff --git a/testsuite/tests/warnings/w06.ml b/testsuite/tests/warnings/w06.ml
index dc4e6e6a6..01b608b85 100644
--- a/testsuite/tests/warnings/w06.ml
+++ b/testsuite/tests/warnings/w06.ml
@@ -10,7 +10,6 @@ compile_only = "true"
 *)
 
 let foo ~bar = ignore bar (* one label *)
-
 let bar ~foo ~baz = ignore (foo, baz) (* two labels *)
 
 let () = foo 2
diff --git a/testsuite/tests/warnings/w33.ml b/testsuite/tests/warnings/w33.ml
index 8fd254477..cea62d564 100644
--- a/testsuite/tests/warnings/w33.ml
+++ b/testsuite/tests/warnings/w33.ml
@@ -25,9 +25,7 @@ module R = struct
 end
 
 let f M.(x) = x (* useless open *)
-
 let g N.(A | B) = () (* used open *)
-
 let h R.{ x } = R.{ x }
 
 open N (* used open *)
@@ -35,5 +33,4 @@ open N (* used open *)
 let i (A | B) = B
 
 open! M (* useless open! *)
-
 open M (* useless open *)
diff --git a/testsuite/tests/warnings/w45.ml b/testsuite/tests/warnings/w45.ml
index 01a5b9f75..f80f62c0e 100644
--- a/testsuite/tests/warnings/w45.ml
+++ b/testsuite/tests/warnings/w45.ml
@@ -21,7 +21,6 @@ end
 
 module T3 = struct
   open T1 (* unused open *)
-
   open T2 (* shadow X, which is later used; but not A, see #6762 *)
 
   let _ = A, X (* X belongs to several types *)
diff --git a/testsuite/tests/warnings/w47_inline.ml b/testsuite/tests/warnings/w47_inline.ml
index dadcb8ab3..6409e9f9e 100644
--- a/testsuite/tests/warnings/w47_inline.ml
+++ b/testsuite/tests/warnings/w47_inline.ml
@@ -10,27 +10,16 @@ compile_only = "true"
 *)
 
 let a = fun [@inline] x -> x (* accepted *)
-
 let b = fun [@inline never] x -> x (* accepted *)
-
 let c = fun [@inline always] x -> x (* accepted *)
-
 let d = fun [@inline malformed attribute] x -> x (* rejected *)
-
 let e = fun [@inline malformed_attribute] x -> x (* rejected *)
-
 let f = fun [@inline: malformed_attribute] x -> x (* rejected *)
-
 let g = fun [@inline? malformed_attribute] x -> x (* rejected *)
-
 let h x = (a [@inlined]) x (* accepted *)
-
 let i x = (a [@inlined never]) x (* accepted *)
-
 let j x = (a [@inlined always]) x (* accepted *)
-
 let k x = (a [@inlined malformed]) x (* rejected *)
-
 let l x = x [@@inline] (* accepted *)
 
 let test x =
diff --git a/testsuite/tests/warnings/w53.ml b/testsuite/tests/warnings/w53.ml
index ffb5da173..93e5711a8 100644
--- a/testsuite/tests/warnings/w53.ml
+++ b/testsuite/tests/warnings/w53.ml
@@ -18,9 +18,7 @@ let i x = (x [@inlined]) (* rejected *)
 let j x = (x [@ocaml.inlined]) (* rejected *)
 
 let k x = (h [@inlined]) x (* accepted *)
-
 let k' x = (h [@ocaml.inlined]) x (* accepted *)
-
 let l x = (h x [@inlined]) (* rejected *)
 
 let m x = (x [@tailcall]) (* rejected *)
@@ -28,9 +26,7 @@ let m x = (x [@tailcall]) (* rejected *)
 let n x = (x [@ocaml.tailcall]) (* rejected *)
 
 let o x = (h [@tailcall]) x (* accepted *)
-
 let p x = (h [@ocaml.tailcall]) x (* accepted *)
-
 let q x = (h x [@tailcall]) (* rejected *)
 
 module type E = sig end
diff --git a/testsuite/tests/warnings/w54.ml b/testsuite/tests/warnings/w54.ml
index 0bb220fc3..32c26d747 100644
--- a/testsuite/tests/warnings/w54.ml
+++ b/testsuite/tests/warnings/w54.ml
@@ -13,5 +13,4 @@ let f = fun [@inline] [@inline never] x -> x
 let g = fun [@inline] [@something_else] [@ocaml.inline] x -> x
 let h x = (g [@inlined] [@ocaml.inlined never]) x
 let v = (fun [@inline] [@inlined] x -> x) 1 (* accepted *)
-
 let i = fun [@inline] x -> x [@@inline]
diff --git a/tools/dumpobj.ml b/tools/dumpobj.ml
index cb8712acf..53a7698b0 100644
--- a/tools/dumpobj.ml
+++ b/tools/dumpobj.ml
@@ -55,7 +55,6 @@ type global_table_entry =
   | Constant of Obj.t
 
 let start = ref 0 (* Position of beg. of code *)
-
 let reloc = ref ([] : (reloc_info * int) list) (* Relocation table *)
 
 let globals = ref ([||] : global_table_entry array) (* Global map *)
diff --git a/tools/ocamlmklib.ml b/tools/ocamlmklib.ml
index 26612b2b3..7b2d54ab4 100644
--- a/tools/ocamlmklib.ml
+++ b/tools/ocamlmklib.ml
@@ -33,42 +33,27 @@ let compiler_path name =
 ;;
 
 let bytecode_objs = ref [] (* .cmo,.cma,.ml,.mli files to pass to ocamlc *)
-
 and native_objs = ref [] (* .cmx,.ml,.mli files to pass to ocamlopt *)
-
 and c_objs = ref []
 (* .o, .a, .obj, .lib, .dll, .dylib, .so files to
                                pass to mksharedlib and ar *)
 
 and caml_libs = ref [] (* -cclib to pass to ocamlc, ocamlopt *)
-
 and caml_opts = ref [] (* -ccopt to pass to ocamlc, ocamlopt *)
-
 and dynlink = ref Config.supports_shared_libraries
 and failsafe = ref false (* whether to fall back on static build only *)
-
 and c_libs = ref [] (* libs to pass to mksharedlib and ocamlc -cclib *)
-
 and c_Lopts = ref [] (* options to pass to mksharedlib and ocamlc -cclib *)
-
 and c_opts = ref [] (* options to pass to mksharedlib and ocamlc -ccopt *)
-
 and ld_opts = ref [] (* options to pass only to the linker *)
-
 and ocamlc = ref (compiler_path "ocamlc")
 and ocamlc_opts = ref [] (* options to pass only to ocamlc *)
-
 and ocamlopt = ref (compiler_path "ocamlopt")
 and ocamlopt_opts = ref [] (* options to pass only to ocamlc *)
-
 and output = ref "a" (* Output name for OCaml part of library *)
-
 and output_c = ref "" (* Output name for C part of library *)
-
 and rpath = ref [] (* rpath options *)
-
 and debug = ref false (* -g option *)
-
 and verbose = ref false
 
 let starts_with s pref =
diff --git a/typing/ctype.ml b/typing/ctype.ml
index 2e66983fc..274ec80d9 100644
--- a/typing/ctype.ml
+++ b/typing/ctype.ml
@@ -1878,7 +1878,6 @@ let rec occur_rec env allow_recursive visited ty0 ty =
 ;;
 
 let type_changed = ref false (* trace possible changes to the studied type *)
-
 let merge r b = if b then r := true
 
 let occur env ty0 ty =
@@ -4675,7 +4674,6 @@ let match_class_declarations env patt_params patt_type subj_params subj_type =
    [level] number of expansions/enlargement allowed on this branch *)
diff --git a/lambda/translmod.ml b/lambda/translmod.ml
index b28306591..ded91041b 100644
--- a/lambda/translmod.ml
+++ b/lambda/translmod.ml
@@ -1510,9 +1510,7 @@ let transl_store_implementation module_name (str, restr) =
 
 let toploop_ident = Ident.create_persistent "Toploop"
 let toploop_getvalue_pos = 0 (* position of getvalue in module Toploop *)
-
 let toploop_setvalue_pos = 1 (* position of setvalue in module Toploop *)
-
 let aliased_idents = ref Ident.empty
 
 let set_toplevel_unique_name id =
diff --git a/lambda/translobj.mli b/lambda/translobj.mli
index e642dadb1..7320d5091 100644
--- a/lambda/translobj.mli
+++ b/lambda/translobj.mli
@@ -22,7 +22,6 @@ val reset_labels : unit -> unit
 val transl_label_init : (unit -> lambda * 'a) -> lambda * 'a
 val transl_store_label_init : Ident.t -> int -> ('a -> lambda) -> 'a -> int * l
ambda
 val method_ids : Ident.Set.t ref (* reset when starting a new wrapper *)
-
 val oo_wrap : Env.t -> bool -> ('a -> lambda) -> 'a -> lambda
 val oo_add_class : Ident.t -> Env.t * bool
 val reset : unit -> unit
diff --git a/middle_end/flambda/simple_value_approx.ml b/middle_end/flambda/simp
le_value_approx.ml
index 4f2ecb3c4..7e362ad29 100644
--- a/middle_end/flambda/simple_value_approx.ml
+++ b/middle_end/flambda/simple_value_approx.ml
@@ -660,8 +660,10 @@ let get_field t ~field_index:i : get_field_result =
   | Value_string _ | Value_float _ | Value_boxed_int _ ->
     (* The user is doing something unsafe. *)
     Unreachable
-  | Value_set_of_closures _ | Value_closure _ (* This is used by [CamlinternalM
od]. *)
-  | Value_symbol _ | Value_extern _ ->
+  | Value_set_of_closures _
+  | Value_closure _ (* This is used by [CamlinternalMod]. *)
+  | Value_symbol _
+  | Value_extern _ ->
     (* These should have been resolved. *)
     Ok (value_unknown Other)
   | Value_unknown reason -> Ok (value_unknown reason)
diff --git a/ocamldoc/odoc_sig.ml b/ocamldoc/odoc_sig.ml
index dd4088ee5..ca9640f21 100644
--- a/ocamldoc/odoc_sig.ml
+++ b/ocamldoc/odoc_sig.ml
@@ -713,7 +713,8 @@ functor
                 ; ic_text = text_opt
                 }
               | Parsetree.Pcty_open _ (* one could also traverse the open *)
-              | Parsetree.Pcty_signature _ | Parsetree.Pcty_arrow _ ->
+              | Parsetree.Pcty_signature _
+              | Parsetree.Pcty_arrow _ ->
                 (* we don't have a name for the class signature, so we call it "object ... end"  *)
                 { ic_name = Odoc_messages.object_end
                 ; ic_class = None
diff --git a/stdlib/obj.mli b/stdlib/obj.mli
index 7cc823ef0..00c58aa66 100644
--- a/stdlib/obj.mli
+++ b/stdlib/obj.mli
@@ -88,7 +88,6 @@ val forward_tag : int
 val no_scan_tag : int
 val abstract_tag : int
 val string_tag : int (* both [string] and [bytes] *)
-
 val double_tag : int
 val double_array_tag : int
 val custom_tag : int
diff --git a/testsuite/tests/asmcomp/is_static.ml b/testsuite/tests/asmcomp/is_static.ml
index 315070db7..3eee2bbcc 100644
--- a/testsuite/tests/asmcomp/is_static.ml
+++ b/testsuite/tests/asmcomp/is_static.ml
@@ -26,7 +26,6 @@ let () = (f [@inlined never]) ()
 
 (* Closed functions should be static *)
 let closed_function x = x + 1 (* + is a primitive, it cannot be in the closure*)
-
 let () = assert (is_in_static_data closed_function)
 
 (* And functions using closed functions *)
diff --git a/testsuite/tests/lib-dynlink-private/test.ml b/testsuite/tests/lib-dynlink-private/test.ml
index 7cd1c2e09..aef225431 100644
--- a/testsuite/tests/lib-dynlink-private/test.ml
+++ b/testsuite/tests/lib-dynlink-private/test.ml
@@ -168,7 +168,6 @@ all_modules = "sheep.cmx test.cmx"
 *)
 
 let () = Sheep.baa Sheep.s (* Use Sheep module *)
-
 let _ = fun (x : Pig.t) -> x (* Reference Pig module *)
 
 (* Test that a privately loaded module cannot have the same name as a
diff --git a/testsuite/tests/misc-unsafe/almabench.ml b/testsuite/tests/misc-unsafe/almabench.ml
index 50bb92ce2..3ba24f93e 100644
--- a/testsuite/tests/misc-unsafe/almabench.ml
+++ b/testsuite/tests/misc-unsafe/almabench.ml
@@ -45,7 +45,6 @@ and gaussk = 0.01720209895
 
 (* number of days to include in test *)
 let test_loops = 5 (* was: 20 *)
-
 and test_length = 36525
 
 (* sin and cos of j2000 mean obliquity (iau 1976) *)
diff --git a/testsuite/tests/no-alias-deps/aliases.ml b/testsuite/tests/no-alias-deps/aliases.ml
index ab01568b8..34702cb43 100644
--- a/testsuite/tests/no-alias-deps/aliases.ml
+++ b/testsuite/tests/no-alias-deps/aliases.ml
@@ -12,11 +12,8 @@ program = "aliases.cmo"
 *)
 
 module A' = A (* missing a.cmi *)
-
 module B' = B (* broken b.cmi *)
-
 module C' = C (* valid c.cmi *)
-
 module D' = D (* valid d.cmi *)
 
 let () = print_int D'.something
diff --git a/testsuite/tests/regression/pr9326/gc_set.ml b/testsuite/tests/regression/pr9326/gc_set.ml
index 80fc2a696..656d9e3c6 100644
--- a/testsuite/tests/regression/pr9326/gc_set.ml
+++ b/testsuite/tests/regression/pr9326/gc_set.ml
@@ -4,10 +4,8 @@
 open Gc
 
 let min_heap_sz = 524288 (* 512k *)
-
 let space_overhead = 70
 let stack_limit = 4194304 (* 4M *)
-
 let custom_major_ratio = 40
 let custom_minor_ratio = 99
 let custom_minor_max_size = 4096
diff --git a/testsuite/tests/typing-gadts/pr7214.ml b/testsuite/tests/typing-gadts/pr7214.ml
index ab059fe72..a7474e548 100644
--- a/testsuite/tests/typing-gadts/pr7214.ml
+++ b/testsuite/tests/typing-gadts/pr7214.ml
@@ -7,7 +7,6 @@ type _ t = I : int t
 let f (type a) (x : a t) =
   let module M = struct
     let (I : a t) = x (* fail because of toplevel let *)
-
     let x = (I : a t)
   end
   in
@@ -35,7 +34,6 @@ let bad (type a) =
       val e : (int, a) eq
     end = struct
       let (Refl : (int, a) eq) = M.e (* must fail for soundness *)
-
       let e : (int, a) eq = Refl
     end
   end
diff --git a/testsuite/tests/typing-misc/injectivity.ml b/testsuite/tests/typing-misc/injectivity.ml
index 33490a9d0..74d4aff76 100644
--- a/testsuite/tests/typing-misc/injectivity.ml
+++ b/testsuite/tests/typing-misc/injectivity.ml
@@ -46,7 +46,6 @@ module M : sig type +!'a t end
 |}]
 
 type _ t = M : 'a -> 'a M.t t (* OK *)
-
 type 'a u = 'b constraint 'a = 'b M.t
 
 [%%expect {|
diff --git a/testsuite/tests/typing-signatures/els.ml b/testsuite/tests/typing-signatures/els.ml
index a70101f2f..e7ded5f02 100644
--- a/testsuite/tests/typing-signatures/els.ml
+++ b/testsuite/tests/typing-signatures/els.ml
@@ -7,9 +7,7 @@
 
 module type VALUE = sig
   type value (* a Lua value *)
-
   type state (* the state of a Lua interpreter *)
-
   type usert (* a user-defined value *)
 end
 
diff --git a/testsuite/tests/warnings/w06.ml b/testsuite/tests/warnings/w06.ml
index dc4e6e6a6..01b608b85 100644
--- a/testsuite/tests/warnings/w06.ml
+++ b/testsuite/tests/warnings/w06.ml
@@ -10,7 +10,6 @@ compile_only = "true"
 *)
 
 let foo ~bar = ignore bar (* one label *)
-
 let bar ~foo ~baz = ignore (foo, baz) (* two labels *)
 
 let () = foo 2
diff --git a/testsuite/tests/warnings/w33.ml b/testsuite/tests/warnings/w33.ml
index 8fd254477..cea62d564 100644
--- a/testsuite/tests/warnings/w33.ml
+++ b/testsuite/tests/warnings/w33.ml
@@ -25,9 +25,7 @@ module R = struct
 end
 
 let f M.(x) = x (* useless open *)
-
 let g N.(A | B) = () (* used open *)
-
 let h R.{ x } = R.{ x }
 
 open N (* used open *)
@@ -35,5 +33,4 @@ open N (* used open *)
 let i (A | B) = B
 
 open! M (* useless open! *)
-
 open M (* useless open *)
diff --git a/testsuite/tests/warnings/w45.ml b/testsuite/tests/warnings/w45.ml
index 01a5b9f75..f80f62c0e 100644
--- a/testsuite/tests/warnings/w45.ml
+++ b/testsuite/tests/warnings/w45.ml
@@ -21,7 +21,6 @@ end
 
 module T3 = struct
   open T1 (* unused open *)
-
   open T2 (* shadow X, which is later used; but not A, see #6762 *)
 
   let _ = A, X (* X belongs to several types *)
diff --git a/testsuite/tests/warnings/w47_inline.ml b/testsuite/tests/warnings/w47_inline.ml
index dadcb8ab3..6409e9f9e 100644
--- a/testsuite/tests/warnings/w47_inline.ml
+++ b/testsuite/tests/warnings/w47_inline.ml
@@ -10,27 +10,16 @@ compile_only = "true"
 *)
 
 let a = fun [@inline] x -> x (* accepted *)
-
 let b = fun [@inline never] x -> x (* accepted *)
-
 let c = fun [@inline always] x -> x (* accepted *)
-
 let d = fun [@inline malformed attribute] x -> x (* rejected *)
-
 let e = fun [@inline malformed_attribute] x -> x (* rejected *)
-
 let f = fun [@inline: malformed_attribute] x -> x (* rejected *)
-
 let g = fun [@inline? malformed_attribute] x -> x (* rejected *)
-
 let h x = (a [@inlined]) x (* accepted *)
-
 let i x = (a [@inlined never]) x (* accepted *)
-
 let j x = (a [@inlined always]) x (* accepted *)
-
 let k x = (a [@inlined malformed]) x (* rejected *)
-
 let l x = x [@@inline] (* accepted *)
 
 let test x =
diff --git a/testsuite/tests/warnings/w53.ml b/testsuite/tests/warnings/w53.ml
index ffb5da173..93e5711a8 100644
--- a/testsuite/tests/warnings/w53.ml
+++ b/testsuite/tests/warnings/w53.ml
@@ -18,9 +18,7 @@ let i x = (x [@inlined]) (* rejected *)
 let j x = (x [@ocaml.inlined]) (* rejected *)
 
 let k x = (h [@inlined]) x (* accepted *)
-
 let k' x = (h [@ocaml.inlined]) x (* accepted *)
-
 let l x = (h x [@inlined]) (* rejected *)
 
 let m x = (x [@tailcall]) (* rejected *)
@@ -28,9 +26,7 @@ let m x = (x [@tailcall]) (* rejected *)
 let n x = (x [@ocaml.tailcall]) (* rejected *)
 
 let o x = (h [@tailcall]) x (* accepted *)
-
 let p x = (h [@ocaml.tailcall]) x (* accepted *)
-
 let q x = (h x [@tailcall]) (* rejected *)
 
 module type E = sig end
diff --git a/testsuite/tests/warnings/w54.ml b/testsuite/tests/warnings/w54.ml
index 0bb220fc3..32c26d747 100644
--- a/testsuite/tests/warnings/w54.ml
+++ b/testsuite/tests/warnings/w54.ml
@@ -13,5 +13,4 @@ let f = fun [@inline] [@inline never] x -> x
 let g = fun [@inline] [@something_else] [@ocaml.inline] x -> x
 let h x = (g [@inlined] [@ocaml.inlined never]) x
 let v = (fun [@inline] [@inlined] x -> x) 1 (* accepted *)
-
 let i = fun [@inline] x -> x [@@inline]
diff --git a/tools/dumpobj.ml b/tools/dumpobj.ml
index cb8712acf..53a7698b0 100644
--- a/tools/dumpobj.ml
+++ b/tools/dumpobj.ml
@@ -55,7 +55,6 @@ type global_table_entry =
   | Constant of Obj.t
 
 let start = ref 0 (* Position of beg. of code *)
-
 let reloc = ref ([] : (reloc_info * int) list) (* Relocation table *)
 
 let globals = ref ([||] : global_table_entry array) (* Global map *)
diff --git a/tools/ocamlmklib.ml b/tools/ocamlmklib.ml
index 26612b2b3..7b2d54ab4 100644
--- a/tools/ocamlmklib.ml
+++ b/tools/ocamlmklib.ml
@@ -33,42 +33,27 @@ let compiler_path name =
 ;;
 
 let bytecode_objs = ref [] (* .cmo,.cma,.ml,.mli files to pass to ocamlc *)
-
 and native_objs = ref [] (* .cmx,.ml,.mli files to pass to ocamlopt *)
-
 and c_objs = ref []
 (* .o, .a, .obj, .lib, .dll, .dylib, .so files to
                                pass to mksharedlib and ar *)
 
 and caml_libs = ref [] (* -cclib to pass to ocamlc, ocamlopt *)
-
 and caml_opts = ref [] (* -ccopt to pass to ocamlc, ocamlopt *)
-
 and dynlink = ref Config.supports_shared_libraries
 and failsafe = ref false (* whether to fall back on static build only *)
-
 and c_libs = ref [] (* libs to pass to mksharedlib and ocamlc -cclib *)
-
 and c_Lopts = ref [] (* options to pass to mksharedlib and ocamlc -cclib *)
-
 and c_opts = ref [] (* options to pass to mksharedlib and ocamlc -ccopt *)
-
 and ld_opts = ref [] (* options to pass only to the linker *)
-
 and ocamlc = ref (compiler_path "ocamlc")
 and ocamlc_opts = ref [] (* options to pass only to ocamlc *)
-
 and ocamlopt = ref (compiler_path "ocamlopt")
 and ocamlopt_opts = ref [] (* options to pass only to ocamlc *)
-
 and output = ref "a" (* Output name for OCaml part of library *)
-
 and output_c = ref "" (* Output name for C part of library *)
-
 and rpath = ref [] (* rpath options *)
-
 and debug = ref false (* -g option *)
-
 and verbose = ref false
 
 let starts_with s pref =
diff --git a/typing/ctype.ml b/typing/ctype.ml
index 2e66983fc..274ec80d9 100644
--- a/typing/ctype.ml
+++ b/typing/ctype.ml
@@ -1878,7 +1878,6 @@ let rec occur_rec env allow_recursive visited ty0 ty =
 ;;
 
 let type_changed = ref false (* trace possible changes to the studied type *)
-
 let merge r b = if b then r := true
 
 let occur env ty0 ty =
@@ -4675,7 +4674,6 @@ let match_class_declarations env patt_params patt_type subj_params subj_type =
    [level] number of expansions/enlargement allowed on this branch *)
 
 let warn = ref false (* whether double coercion might do better *)
-
 let pred_expand n = if n mod 2 = 0 && n > 0 then pred n else n
 let pred_enlarge n = if n mod 2 = 1 then pred n else n
 
diff --git a/typing/types.mli b/typing/types.mli
index 7b12a87d2..bbdb27137 100644
--- a/typing/types.mli
+++ b/typing/types.mli
@@ -404,13 +404,9 @@ module Variance : sig
   (* both negative and positive occurrences *)
 
   val null : t (* no occurrence *)
-
   val full : t (* strictly invariant (all flags) *)
-
   val covariant : t (* strictly covariant (May_pos, Pos and Inj) *)
-
   val unknown : t (* allow everything, guarantee nothing *)
-
   val union : t -> t -> t
   val inter : t -> t -> t
   val subset : t -> t -> bool
@@ -418,9 +414,7 @@ module Variance : sig
   val set : f -> bool -> t -> t
   val mem : f -> t -> bool
   val conjugate : t -> t (* exchange positive and negative *)
-
   val get_upper : t -> bool * bool (* may_pos, may_neg   *)
-
   val get_lower : t -> bool * bool * bool * bool (* pos, neg, inv, inj *)
 
   (** The most pessimistic variance for a completely unknown type. *)
diff --git a/utils/clflags.ml b/utils/clflags.ml
index 06144ab72..9197ebd75 100644
--- a/utils/clflags.ml
+++ b/utils/clflags.ml
@@ -51,200 +51,122 @@ and dllibs = ref ([] : string list)
 (* .so and -dllib -lxxx *)
 
 let compile_only = ref false (* -c *)
-
 and output_name = ref (None : string option) (* -o *)
 
 and include_dirs = ref ([] : string list) (* -I *)
 
 and no_std_include = ref false (* -nostdlib *)
-
 and print_types = ref false (* -i *)
-
 and make_archive = ref false (* -a *)
-
 and debug = ref false (* -g *)
-
 and debug_full = ref false (* For full DWARF support *)
-
 and unsafe = ref false (* -unsafe *)
-
 and use_linscan = ref false (* -linscan *)
-
 and link_everything = ref false (* -linkall *)
-
 and custom_runtime = ref false (* -custom *)
-
 and no_check_prims = ref false (* -no-check-prims *)
-
 and bytecode_compatible_32 = ref false (* -compat-32 *)
-
 and output_c_object = ref false (* -output-obj *)
-
 and output_complete_object = ref false (* -output-complete-obj *)
-
 and output_complete_executable = ref false (* -output-complete-exe *)
-
 and all_ccopts = ref ([] : string list) (* -ccopt *)
 
 and classic = ref false (* -nolabels *)
-
 and nopervasives = ref false (* -nopervasives *)
-
 and match_context_rows = ref 32 (* -match-context-rows *)
-
 and preprocessor = ref (None : string option) (* -pp *)
 
 and all_ppx = ref ([] : string list)
 (* -ppx *)
 
 let absname = ref false (* -absname *)
-
 let annotations = ref false (* -annot *)
 
 let binary_annotations = ref false (* -bin-annot *)
-
 and use_threads = ref false (* -thread *)
-
 and noassert = ref false (* -noassert *)
-
 and verbose = ref false (* -verbose *)
-
 and noversion = ref false (* -no-version *)
-
 and noprompt = ref false (* -noprompt *)
-
 and nopromptcont = ref false (* -nopromptcont *)
-
 and init_file = ref (None : string option) (* -init *)
 
 and noinit = ref false (* -noinit *)
-
 and open_modules = ref [] (* -open *)
-
 and use_prims = ref "" (* -use-prims ... *)
-
 and use_runtime = ref "" (* -use-runtime ... *)
-
 and plugin = ref false (* -plugin ... *)
-
 and principal = ref false (* -principal *)
-
 and real_paths = ref true (* -short-paths *)
-
 and recursive_types = ref false (* -rectypes *)
-
 and strict_sequence = ref false (* -strict-sequence *)
-
 and strict_formats = ref false (* -strict-formats *)
-
 and applicative_functors = ref true (* -no-app-funct *)
-
 and make_runtime = ref false (* -make-runtime *)
-
 and c_compiler = ref (None : string option) (* -cc *)
 
 and no_auto_link = ref false (* -noautolink *)
-
 and dllpaths = ref ([] : string list) (* -dllpath *)
 
 and make_package = ref false (* -pack *)
-
 and for_package = ref (None : string option) (* -for-pack *)
 
 and error_size = ref 500 (* -error-size *)
-
 and float_const_prop = ref true (* -no-float-const-prop *)
-
 and transparent_modules = ref false
 (* -trans-mod *)
 
 let unique_ids = ref true (* -d(no-)unique-ds *)
-
 let locations = ref true (* -d(no-)locations *)
-
 let dump_source = ref false (* -dsource *)
 
 let dump_parsetree = ref false (* -dparsetree *)
-
 and dump_typedtree = ref false (* -dtypedtree *)
-
 and dump_shape = ref false (* -dshape *)
-
 and dump_rawlambda = ref false (* -drawlambda *)
-
 and dump_lambda = ref false (* -dlambda *)
-
 and dump_rawclambda = ref false (* -drawclambda *)
-
 and dump_clambda = ref false (* -dclambda *)
-
 and dump_rawflambda = ref false (* -drawflambda *)
-
 and dump_flambda = ref false (* -dflambda *)
-
 and dump_flambda_let = ref (None : int option) (* -dflambda-let=... *)
 
 and dump_flambda_verbose = ref false (* -dflambda-verbose *)
-
 and dump_instr = ref false (* -dinstr *)
-
 and keep_camlprimc_file = ref false
 (* -dcamlprimc *)
 
 let keep_asm_file = ref false (* -S *)
 
 let optimize_for_speed = ref true (* -compact *)
-
 and opaque = ref false (* -opaque *)
-
 and dump_cmm = ref false
 (* -dcmm *)
 
 let dump_selection = ref false (* -dsel *)
-
 let dump_cse = ref false (* -dcse *)
-
 let dump_live = ref false (* -dlive *)
-
 let dump_spill = ref false (* -dspill *)
-
 let dump_split = ref false (* -dsplit *)
-
 let dump_interf = ref false (* -dinterf *)
-
 let dump_prefer = ref false (* -dprefer *)
-
 let dump_regalloc = ref false (* -dalloc *)
-
 let dump_reload = ref false (* -dreload *)
-
 let dump_scheduling = ref false (* -dscheduling *)
-
 let dump_linear = ref false (* -dlinear *)
-
 let dump_interval = ref false (* -dinterval *)
-
 let keep_startup_file = ref false (* -dstartup *)
-
 let dump_combine = ref false (* -dcombine *)
-
 let profile_columns : Profile.column list ref = ref [] (* -dprofile/-dtimings *)
-
 let native_code = ref false (* set to true under ocamlopt *)
-
 let force_tmc = ref false (* -force-tmc *)
-
 let force_slash = ref false (* for ocamldep *)
-
 let clambda_checks = ref false (* -clambda-checks *)
-
 let cmm_invariants = ref Config.with_cmm_invariants (* -dcmm-invariants *)
-
 let flambda_invariant_checks = ref Config.with_flambda_invariants
 (* -flambda-(no-)invariants *)
 
 let dont_write_files = ref false (* set to true under ocamldoc *)
-
 let insn_sched_default = true
 let insn_sched = ref insn_sched_default (* -[no-]insn-sched *)
 
@@ -254,7 +176,6 @@ let std_include_flag prefix =
 
 let std_include_dir () = if !no_std_include then [] else [ Config.standard_library ]
 let shared = ref false (* -shared *)
-
 let dlcode = ref true (* not -nodynlink *)
 
 let pic_code =
@@ -278,7 +199,6 @@ let with_runtime = ref true
 (* -with-runtime *)
 
 let keep_docs = ref false (* -keep-docs *)
-
 let keep_locs = ref true (* -keep-locs *)
 
 let unsafe_string =
@@ -288,17 +208,11 @@ let unsafe_string =
 (* -safe-string / -unsafe-string *)
 
 let classic_inlining = ref false (* -Oclassic *)
-
 let inlining_report = ref false (* -inlining-report *)
-
 let afl_instrument = ref Config.afl_instrument (* -afl-instrument *)
-
 let afl_inst_ratio = ref 100 (* -afl-inst-ratio *)
-
 let function_sections = ref false (* -function-sections *)
-
 let simplify_rounds = ref None (* -rounds *)
-
 let default_simplify_rounds = ref 1 (* -rounds *)
 
 let rounds () =
@@ -339,13 +253,10 @@ let inline_lifting_benefit = ref (Int_arg_helper.default default_inline_lifting_
 let inline_max_unroll = ref (Int_arg_helper.default default_inline_max_unroll)
 let inline_max_depth = ref (Int_arg_helper.default default_inline_max_depth)
 let unbox_specialised_args = ref true (* -no-unbox-specialised-args *)
-
 let unbox_free_vars_of_closures = ref true
 let unbox_closures = ref false (* -unbox-closures *)
-
 let default_unbox_closures_factor = 10
 let unbox_closures_factor = ref default_unbox_closures_factor (* -unbox-closures-factor *)
-
 let remove_unused_arguments = ref false (* -remove-unused-arguments *)
 
 type inlining_arguments =
@@ -491,7 +402,6 @@ let set_dumped_pass s enabled =
 ;;
 
 let dump_into_file = ref false (* -dump-into-file *)
-
 let dump_dir : string option ref = ref None (* -dump-dir *)
 
 type 'a env_reader =
```

</details>

File: test/passing/tests/js_source.ml.ref (hunk 4 above)
[the remark this answers is not in the document]
Comment (Julow) [reply test/passing/tests/js_source.ml.ref:535]: There are still many instances of this bug. This should be fixed before the next release to avoid having a new intermediate bug between the previous state and the ideal state.

Repro (`profile=conventional`):
```ocaml
let x = foo 1 (* x *)
let y = bar (1 + 1) (* y *)

let z = baz (* z *)
```

**Review by Julow — APPROVED** [review]
Looks good :)

**Comment by aryx** [comment]
yeah!
When will there be a new release of ocamlformat with this fix?

File: test/passing/tests/js_source.ml.ocp [hunk 5]
```diff
@@ -2603,11 +2599,9 @@ let f (Aux x) =
   | Succ (Succ Zero) -> "2"
   | Succ (Succ (Succ Zero)) -> "3"
   | Succ (Succ (Succ (Succ Zero))) -> "4"
-  | _ -> .
+  | _ -> . (* error *)
 ;;
 
-(* error *)
```
Comment (aryx) [inline test/passing/tests/js_source.ml.ocp:2609]: hmm this seems like a regression.
A comment alone on its line marks a section and should not be aggregated to the previous match no?

**Review by aryx — COMMENTED** [review]
cc @gpetiot 
There seems to be some regressions.

**Comment by gpetiot** [comment]
We are waiting for some feedback about the last RPC changes, then I will open some preview PRs to check with project maintainers that there is no regressions. (The ETA will depend on whether there are regressions to fix or not)

File: test/passing/tests/js_source.ml.ocp (hunk 5 above)
Comment (gpetiot) [reply test/passing/tests/js_source.ml.ocp:2609]: Not in this case because the original code to be formatted was:
```ocaml
let f (Aux x) =
  match x with
  | Succ Zero -> "1"
  | Succ (Succ Zero) -> "2"
  | Succ (Succ (Succ Zero)) -> "3"
  | Succ (Succ (Succ (Succ Zero))) -> "4"
  | _ -> .  (* error *)
;;
```
